### ISSUE TITLE
Manual mode isn't working if MyGaze/EyeTribe isn't connected

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#408] opened 2017-10-20 11:03 UTC
Version: 2.11.0

- Set up OptiKey to use MyGaze or EyeTribe (but these aren't installed/connected)
- OptiKey restarts to use the chosen eye tracker
- Obviously eye tracking doesn't work
- Right click -> Manual mode
- OptiKey enters manual mode
- Manual mode doesn't work (no mouse progress is registered, you cannot interact). 

If you do the same thing with GazeTracker or EyeX selected, then manual mode works okay. I haven't tested all the other input options.

I've also replicated this on my Win8.1 PC and another running Win 10.

**Comment by JuliusSweetland** [comment] 2017-10-26 22:19
Fix in 2.12.0 pre_release_2 (https://github.com/OptiKey/OptiKey/releases/tag/v2.12.0_pre-release_2)

**Comment by kmcnaught** [comment] 2017-11-01 12:36
I've just tested this on v2.12.0_pre-release_2 and the bug still exists but later in the workflow:

- Set up to use MyGaze (which isn't installed or connected)
- Launch OptiKey
- You now get the "Uh oh" error message, great
- Turn on manual mode
- Manual mode works
- Turn off manual mode
- Turn on manual mode
- Manual mode does **not** work this time.

**Comment by kmcnaught** [comment] 2017-11-01 12:47
Might be worth noting:
- the above behaviour also occurs with EyeTribe as input
- With the EyeX or Gaze tracker as input the behaviour is as follows: (in the case of EyeX, it is installed but not connected)
    - set up to use [eyex or gazetracker]
    - launch optikey
    - you do not get any error message (perhaps for EyeX this is because the service connects ok, but just responds as being in invalid state)
    - you can toggle manual mode multiple times and it always works...

**Comment by Chopinsky** [comment] 2017-11-02 00:01
The 1st problem seems to be caused by raising 2 roast notification simultaneously -- 1 for manual mode, 1 for error to initialize MyGaze, and only 1 callback to the notification popup are invoked (because the 1st popup thinks it's not closing because the 2nd popup is raised, but it is closing), which mess up the keyboard shield count (in a similar way to the original issue), and hence leaving a shield up even if all popups have been dismissed.

**Comment by JuliusSweetland** [comment] 2017-11-06 17:22
@kmcnaught Fix is now merged into master and will be included in the next release (I have not prepared this yet)

**Closed by JuliusSweetland** 2017-11-06 17:22 UTC
Labels: STATUS:help wanted, TYPE:bug
