### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by rafamedina** [OptiKey/OptiKey#336] opened 2017-07-26 02:35 UTC
I have a weird issue.
I downloaded the installer and after executed it, It runs twice instances.. I forked the repo and tried to reproduce the issue but it runs correctly..
Do you any idea?

By the way, I think (at least i didnt find it), a "delete everything button" is required, or keep the cursor three times or something like that in the backspace and clear the input field.

**Comment by JuliusSweetland** [comment] 2017-07-26 15:26
@SirRafaMedina That's very odd. I haven't encountered that. Can you please restart and try again, ensuring you only single (left) click the icon on the taskbar at the bottom (or double click the icon if it is on the desktop).

Regarding a "delete everything" key - this is accomplished using the CLEAR key on the left of the scratchpad (where the text appears).

**Comment by JuliusSweetland** [comment] 2017-08-01 08:02
Closing as no new details and unable to reproduce the issue.

**Closed by JuliusSweetland** 2017-08-01 08:02 UTC
