### ISSUE TITLE
Dynamic keyboard font size

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#574] opened 2019-07-24 19:50 UTC
I wanted a stripped version of the default alpha keyboard so I made a dynamic keyboard. Why isn't the font size on the keys as big as it is on the default keyboard? The keys on my dynamic keyboard are big enough for the letters to fit properly. It's just a visual thing, but still.

A few additional questions, if you don't mind. What are BorderThickness and SymbolMargin tags? How exactly does the Height tag work? Does it need OptiKey to be docked? (I understand why docked mode exists but I hate it because it messes up my desktop icons and window sizes. I don't use OptiKey all the time. I only need it when typing long texts.)

**Comment by JuliusSweetland** [comment] 2019-07-26 13:04
Hi Lsaranto,

1.Text size on keys is determined automatically. Keys are grouped into 3 sets: keys with symbols and text, keys with symbols only, and keys with text only. Keys which span more than one row or column are split out and treated separately. Now within each group a font size is determined so all keys have the same font size. Essentially this means you need to look for keys with long text strings on them - these will force all other keys in the same group to have to use a smaller font.

2.BorderThickness = border around the whole keyboard. For some users making selections at the edges of the keyboard might be difficult - this provides one way of increasing the margin so that the keys are pushed in from the edges. The larger the margin the less space there is for the keys, so be aware of that.

3.SymbolMargin = How much of a margin/padding is added in each key around the symbol (if there is one).

4.Height = height of Optikey (by default this is the docked height).

5.Does it have to be docked? No, you can use the Size & Position keyboard (from the menu) to move OptiKey away from the docked edge - it will then break free and float over your other applications. When you close OptiKey it will remember where it was and should open in the same state.

**Comment by lsaranto** [comment] 2019-07-26 15:43
1. Ok, I get the logic.

Just for reference, here's the default keyboard on my screen.

![OptiKey_2019-07-24_18-32-19](https://user-images.githubusercontent.com/52409168/61962508-51b01d00-afd2-11e9-9e34-3b5d97ee3587.png)

And here's the dynamic keyboard I've made. The cells are all 1 high and 2 wide.

![OptiKey_2019-07-26_17-52-50](https://user-images.githubusercontent.com/52409168/61962709-caaf7480-afd2-11e9-8559-6baed1b76cf4.png)

Certainly, there's room for the text to be bigger?

5. Yes, size & position adjustments were a happy discovery I, fortunately, made early on. Otherwise, I even might not have given OptiKey a chance because it was taking so much desktop space.

6. Symbols on a dynamic keyboard don't show a label when highlighted. It doesn't really matter to me. I just noticed an inconsistency to the default keyboard.

**Comment by JuliusSweetland** [comment] 2019-07-28 13:23
@lsaranto Thanks for pointing this out. I've just made a change to the way the SharedSizeGroup is determined. It now renders single characters on keys much larger. I'll create an installer later today once I've finished looking at another issue.

Regarding the labels on symbol keys - this does work. Just set a "<Label>TEXT</Label>" on an action key.

**Comment by lsaranto** [comment] 2019-07-30 08:23
Going back to the Height tag. You said: "by default this is the docked height". So do you mean I can change it somehow? If not, would you consider
 changing the code so that the Height tag has an effect also when Optikey is not docked? Or maybe add another tag?

**Comment by JuliusSweetland** [comment] 2019-07-30 10:40
@lsaranto Yes, the height tag in a dynamic keyboard only currently effects the docked height. I can possibly take a look into making this work when floating as well, but it requires a bit of work

**Comment by JorgeMattos** [comment] 2019-07-31 04:27
This is because ctrl ends up decreasing the others, puts ct below rl, or uses one and a half key for ctrl. Look at the sprint.
![Capturar](https://user-images.githubusercontent.com/39384525/62183919-607c3400-b332-11e9-844f-0921a8c8b2ea.JPG)

**Comment by JuliusSweetland** [comment] 2019-07-31 10:14
Hi Jorge. It partly is that, but it was mainly because keys with a single
character and keys with multiple characters (eg CTRL) were being grouped
together for sizing purposes. I have split them out and now single
characters are being rendered much larger.

**Comment by JorgeMattos** [comment] 2019-08-04 18:15
Sorry I'm absent, I'm writing a Technical site about Optikey + tobii in Portuguese.
I really wanted an interview from you Julius Sweetland?
The Site will be called Voice ALS.
https://vozela.org

**Comment by JuliusSweetland** [comment] 2019-08-05 06:28
Hi Jorge. Sure that will be fine. When would you like to do that?

**Comment by JorgeMattos** [comment] 2019-08-07 15:56
I am creating a form with the questions.
When you're done I'll send the link,
Thank you so much for everything you have done for us impatiently from ALS.
We love you...

**Comment by JuliusSweetland** [comment] 2019-08-07 17:13
You're welcome. Looking forward to the website.

**Comment by JorgeMattos** [comment] 2019-09-24 14:48
Something went wrong with the dynamic keyboard version 2.25.0
I'm making a video, and I will upload the files here ok?
There were a lot of dynamic keyboard changes, I couldn't keep up with all of them, I'm reading ...

**Comment by AdamRoden** [comment] 2019-09-24 15:05
@JorgeMattos If you are referring to the back and forth between myself and Julius about dynamic keyboards, don't worry about any of that. It's all conceptual, and none of it is in version 2.25.0. 

Otherwise, can you share your dynamic keyboard file along with explaining what's wrong?

**Comment by JuliusSweetland** [comment] 2019-09-24 15:15
@JorgeMattos @AdamRoden There was one commit in this release which impacts the Dynamic Keyboard logic, but I believe the change fixes something which was wrong. You may be seeing a different rendering of your dynamic keyboard(s), so if you could give us some more details we can take a look.

The commit is this one: https://github.com/OptiKey/OptiKey/commit/53e2a2e7d62327a21385d56273a465445f6be5be

**Comment by JuliusSweetland** [comment] 2019-09-24 15:18
The two logic changes in that class are:

https://github.com/OptiKey/OptiKey/commit/53e2a2e7d62327a21385d56273a465445f6be5be#diff-c4f634b466d36bb22813b911af03a5c9R167

and

https://github.com/OptiKey/OptiKey/commit/53e2a2e7d62327a21385d56273a465445f6be5be#diff-c4f634b466d36bb22813b911af03a5c9R173

**Comment by JorgeMattos** [comment] 2019-09-24 15:49
@AdamRoden  Let's take it easy. Excuse me!
I wasn't referring to you.
There is a problem with the font size.
Has problem with dynamic keyboard height below 50%.
It ignores the height value dow dynamic keyboard.
Already post the video and files.

**Comment by JuliusSweetland** [comment] 2019-09-24 16:03
@JorgeMattos I cannot see the video and files - where are please?

**Comment by JorgeMattos** [comment] 2019-09-24 16:05
I'm going up to YouTube.

**Comment by JorgeMattos** [comment] 2019-09-24 20:21
Sorry for the delay.
[Dinamic keyboard - Jorge Mattos.zip](https://github.com/OptiKey/OptiKey/files/3649281/Dinamic.keyboard.-.Jorge.Mattos.zip)


https://youtu.be/OPiCtIlL2IU

**Comment by AdamRoden** [comment] 2019-09-24 22:17
I watched the video and have 2 observations:
1. In all versions, when @JorgeMattos runs the installer, the listener from the closed instance continues to make noise. It is another example of issue #592.
2. In v2.25, when a key spans multiple columns, the OptiKey is auto-sizing the label to fit in 1 column, thus making it smaller.

**Comment by AdamRoden** [comment] 2019-09-24 23:11
@JuliusSweetland I tested some new code on my machine and it works better. Read the comment I added to the commit to see what I did.
https://github.com/OptiKey/OptiKey/commit/53e2a2e7d62327a21385d56273a465445f6be5be#r35221735

**Comment by JorgeMattos** [comment] 2019-09-24 23:56
@AdamRoden     Did you compile?

**Comment by JorgeMattos** [comment] 2019-09-24 23:57
Is there an error on my dynamic keyboard?

**Comment by AdamRoden** [comment] 2019-09-25 01:05
@JorgeMattos I'm not sure I know what you are looking for. I compiled and tested locally on my machine. 
On my machine, after I build and test my code in Visual Studio, I can copy the OptiKey.exe file from my Visual Studio bin folder and use it to replace the one in my OptiKey install folder. This way I run it as my personal beta release.
@JuliusSweetland What's the best practice for creating and sharing a beta release for someone else to try?

**Comment by JuliusSweetland** [comment] 2019-09-25 10:16
@AdamRoden @JorgeMattos Thank you both for raising this issue and for looking into it. Adam your suggested change pointed me in the right direction. I've implemented a few changes to the code:

1.I was blindly using the width and height to set the key width and height spans. These are not the same thing. The spans are meant to describe when a key spans more than one normal key width or height. In this dynamic keyboard (Meu Teclado.xml) the base keys are all width=2. I have instead added logic to check the smallest key width and smallest key height and then set the spans as multiples of this number should a key be defined as larger.

2.The diacritic keys were being incorrectly sized as their length is greater than one (the circle character, plus the diacritic mark character). I have added code to exclude the circle character from the calculation, as well as to perform a unicode composition on the remaining text, which will cover any cases where the user decides to set the text as a separate character and diacritic character.

3.Unicode font - again for the diacritic keys the circle and diacritic mark are not being combined as for this you need a unicode compatible font. I have added support for this. @JorgeMattos you will need to change your xml so the diacritic keys are defined with the new UseUnicodeCompatibilityFont property set to true:

`        <TextKey>
            <Label>&#x25CC;&#x0301;</Label>
            <Text>&#x0301;</Text>
            <Width>3</Width>
            <Row>0</Row>
            <Col>0</Col>
            <UseUnicodeCompatibilityFont>true</UseUnicodeCompatibilityFont>
        </TextKey>`

**Comment by JuliusSweetland** [comment] 2019-09-25 10:26
FYI these are screenshots showing before:
![Without setting width or height spans](https://user-images.githubusercontent.com/4722561/65592833-3daf7a00-df87-11e9-9241-b41c3846be46.PNG)

After new width and height span logic:
![With setting width or height spans](https://user-images.githubusercontent.com/4722561/65592849-4607b500-df87-11e9-9c8d-2e11f3e56026.PNG)

And finally after adding unicode compatibility font logic (and amending the dynamic keyboard to add the property to the relevant keys):
![With setting width or height spans and unicode compatibility font](https://user-images.githubusercontent.com/4722561/65592884-5586fe00-df87-11e9-984d-6f4077947ec9.PNG)

**Comment by AdamRoden** [comment] 2019-09-25 14:59
@JuliusSweetland  Sorry, but there still is an issue with the width span in v2.26. Check out my triple wide key. It's getting auto-fit to a span of 1, and all the other keys with >1 character are matching its size.

![image](https://user-images.githubusercontent.com/45572061/65612709-55343600-df7a-11e9-8948-306232744585.png)

**Comment by JuliusSweetland** [comment] 2019-09-25 15:08
@AdamRoden Hmm. This is actually behaving as I would expect. The triple width key is being sized so that the text fits one key width. What we actually need here is the ability to exclude a key from auto sizing. I'll look at creating something quickly now. Can you send me your xml to test?

**Comment by AdamRoden** [comment] 2019-09-25 15:20
Here's the keyboard.
[MySymbols - Copy.zip](https://github.com/OptiKey/OptiKey/files/3653299/MySymbols.-.Copy.zip)

**Comment by JuliusSweetland** [comment] 2019-09-25 16:13
@AdamRoden New version (2.27.0) is available now. To make your key work you should set 3 new properties on it:

```
        <AutoScaleToOneKeyWidth>false</AutoScaleToOneKeyWidth>
        <AutoScaleToOneKeyHeight>false</AutoScaleToOneKeyHeight>
        <SharedSizeGroup>IndependentSizeGroup1</SharedSizeGroup>
```

The first two prevent OptiKey trying to size the key's label to fit the equivalent of one key wide and high. The last property allows you to split out that key into a separate sizing group. This is required to stop the wide key from sizing its text in the same group as all the other keys with more than one letter (e.g. "F1").

**Comment by JuliusSweetland** [comment] 2019-09-25 16:15
@AdamRoden Here's a before and after:

Before: 
![image](https://user-images.githubusercontent.com/4722561/65619388-f7beda00-dfb7-11e9-88a0-ebe2169e672c.png)

With AutoScaleToOneKeyWidth and AutoScaleToOneKeyHeight set to false:
![Auto width and height span disabled](https://user-images.githubusercontent.com/4722561/65619431-09a07d00-dfb8-11e9-965c-d1379513938d.PNG)

And finally with the above two properties set, plus an independent SharedSizeGroup:
![Auto width and height span disabled and independent size group](https://user-images.githubusercontent.com/4722561/65619463-16bd6c00-dfb8-11e9-9363-8d33d979a1a0.PNG)

**Comment by JorgeMattos** [comment] 2019-09-25 16:52
Version 2.27.0 Looks great.
I changed ALT to 2 Width and the lyrics were great!
<UseUnicodeCompatibilityFont>true</UseUnicodeCompatibilityFont>  It looks great!
Thanks so much Julius, I will update my XML. You are great!

But the dynamic mouse does not accept height 8.
I have a patient who uses this on the right side.

![2](https://user-images.githubusercontent.com/39384525/65621774-c552b400-df9a-11e9-95d0-dfe97ae564c5.JPG)
![3](https://user-images.githubusercontent.com/39384525/65621775-c5eb4a80-df9a-11e9-8867-7b1823fd1c0e.JPG)
![4](https://user-images.githubusercontent.com/39384525/65621776-c5eb4a80-df9a-11e9-98fc-9c09980262ca.JPG)
![Capturar](https://user-images.githubusercontent.com/39384525/65621777-c5eb4a80-df9a-11e9-9a42-223efe1aee1a.JPG)

[Dinamic keyboard lateral.zip](https://github.com/OptiKey/OptiKey/files/3653751/Dinamic.keyboard.lateral.zip)

**Comment by JuliusSweetland** [comment] 2019-09-25 17:03
@JorgeMattos Glad it's working. Could you give me some more details on the height span of 8 problem?

**Comment by JuliusSweetland** [comment] 2019-09-25 17:04
@JorgeMattos @AdamRoden Could either of you please check the last 2 sections I have added to this wiki page to make sure the new properties are described correctly? I rushed my text so it may need correcting!
https://github.com/OptiKey/OptiKey/wiki/Creating-and-Using-Dynamic-Keyboards

**Comment by JorgeMattos** [comment] 2019-09-25 18:22
https://github.com/OptiKey/OptiKey/wiki/Creating-and-Using-Dynamic-Keyboards
@JuliusSweetland   It was very good!
The images are updated.

**Comment by JorgeMattos** [comment] 2019-09-25 18:37
@JuliusSweetland   Now don't accept dynamic keyboards below 50%?

<Keyboard>
    <Name>Mouse</Name>
    <HideFromKeyboardMenu>True</HideFromKeyboardMenu>
    <Height>8</Height>
    <SymbolMargin>10</SymbolMargin>
    <BorderThickness>1,1,1,1</BorderThickness>
    <Grid>
        <Rows>1</Rows>
        <Cols>10</Cols>
</Grid>

This keyboard appears in 50%
Not by 10%.

![Capturar](https://user-images.githubusercontent.com/39384525/65629753-54b39380-dfaa-11e9-98e6-7bbe74e6c7c3.JPG)

**Comment by JuliusSweetland** [comment] 2019-09-25 22:19
Could you please send over your keyboard XML? Is it the same as you sent
before?

**Comment by JorgeMattos** [comment] 2019-09-26 00:18
Sorry I forgot.
It's messy. It's a little messy ...

[Dinamic keyboard lateral.zip](https://github.com/OptiKey/OptiKey/files/3655301/Dinamic.keyboard.lateral.zip)

**Comment by JuliusSweetland** [comment] 2019-09-26 08:52
@JorgeMattos I'll only be able to look at this tonight. Can you please test and let me know when the right aligned mouse keyboard was last working? In other words which version of OptiKey broke this keyboard layout? Thanks.

**Comment by JorgeMattos** [comment] 2019-09-26 12:38
Ok no hurry, I warned everyone not to update.
In version 2.23 It was good!
In version 2.24 I gave this bug, in mine I did not have this bug in 2.24.
I only gave this bug after I upgraded to 2.25.

**Comment by JuliusSweetland** [comment] 2019-09-26 21:37
@JorgeMattos Please try this pre-release of 2.29.0: https://github.com/OptiKey/OptiKey/releases/tag/v2.29.0

**Comment by JorgeMattos** [comment] 2019-09-27 18:52
@JuliusSweetland    It hasn't worked out yet.
It worked the height of the dynamic mouse.
But other errors appeared.
My computer screen hd 1920 x 1080! I set 125% zum Does this interfere with anything?
I have a computer lab, I will test on it.

**Comment by JuliusSweetland** [comment] 2019-09-27 18:53
After testing could you please describe the new errors so I can
investigate. Thanks

**Comment by JorgeMattos** [comment] 2019-09-27 19:02
Yes yes I aggravate the video tests.
Tomorrow I send the tests.
Thank you!

**Comment by JorgeMattos** [comment] 2019-09-28 21:08
@JuliusSweetland     It really is the same bug in the computer lab.
Upon exiting the dynamic keyboard it changes Optikey's native height.
It is impossible to click!
I'm going to record a video, I'm using TeamViewer to tinker with the computer lab.
New installation, Version 2.29.0.

**Comment by JuliusSweetland** [comment] 2019-09-28 21:10
Yes please do. Please also upload the dynamic keyboard you are using which
resizes OptiKey and allows you to return to the main OptiKey menu so I can
see how the dock height is changed. Thanks.

**Comment by JorgeMattos** [comment] 2019-09-28 22:42
@JuliusSweetland   Only one dynamic keyboard error upon exiting. Strange that!
I'll see then the dynamic (Meu Menu)

https://youtu.be/K0B_XeD70pM
[Meu Teclado.zip](https://github.com/OptiKey/OptiKey/files/3666071/Meu.Teclado.zip)

The one with the problem is not Optikey.
I will rename.

```
<Keyboard>
    <Name>Meu Menu</Name>
    <HideFromKeyboardMenu>True</HideFromKeyboardMenu>
    <Height>44</Height>
    <SymbolMargin>5</SymbolMargin>
    <BorderThickness>1,1,1,1</BorderThickness>
    <Grid>
        <Rows>3</Rows>
        <Cols>4</Cols>
    </Grid>
    <Keys>
		<ChangeKeyboardKey> 
     <Row>0</Row>
     <Col>0</Col>
     <Symbol>AlphaIcon</Symbol>
     <ReturnToThisKeyboard>True</ReturnToThisKeyboard>
     <DestinationKeyboard>Meu Teclado</DestinationKeyboard>
        </ChangeKeyboardKey>
		<ChangeKeyboardKey> 
     <Row>0</Row>
     <Col>1</Col>
     <Symbol>NumericAndSymbolsIcon</Symbol>
     <ReturnToThisKeyboard>True</ReturnToThisKeyboard>
     <DestinationKeyboard>Meu Numeros</DestinationKeyboard>
        </ChangeKeyboardKey>
		<ActionKey>
            <Action>PhysicalKeysKeyboard</Action>
            <Symbol>PhysicalKeysIcon</Symbol>
            <Row>0</Row>
            <Col>2</Col>
        </ActionKey>
		<ActionKey>
            <Action>Restart</Action>
            <Symbol>RestartIcon</Symbol>
            <Label>Reiniciar
Optikey</Label>
            <Row>0</Row>
            <Col>3</Col>
        </ActionKey>
		
        <ActionKey>
            <Action>ConversationAlpha1Keyboard</Action>
            <Symbol>ConversationIcon</Symbol>
            <Row>1</Row>
            <Col>0</Col>
        </ActionKey>
		<ActionKey>
            <Row>1</Row>
            <Col>1</Col>
            <Action>MouseKeyboard</Action>
            <Symbol>MouseIcon</Symbol>
        </ActionKey>
		<ActionKey>
            <Action>Sleep</Action>
            <Symbol>SleepIcon</Symbol>
            <Row>1</Row>
            <Col>3</Col>
        </ActionKey>
		
		<ActionKey>
            <Row>1</Row>
            <Col>2</Col>
            <Action>MenuKeyboard</Action>
		    <Label>Sair do
Dinâmico</Label>
            <Symbol>KeyboardIcon</Symbol>
        </ActionKey>
		<ActionKey>
            <Action>DecreaseOpacity</Action>
            <Symbol>DecreaseOpacityIcon</Symbol>
            <Row>2</Row>
            <Col>0</Col>
        </ActionKey>
		<ActionKey>
            <Action>IncreaseOpacity</Action>
            <Symbol>IncreaseOpacityIcon</Symbol>
            <Row>2</Row>
            <Col>1</Col>
        </ActionKey>
		<ActionKey>
            <Action>Minimise</Action>
            <Symbol>MinimiseIcon</Symbol>
            <Row>2</Row>
            <Col>2</Col>
        </ActionKey>
	    <ActionKey>
            <Action>Calibrate</Action>
			<Label>CALIBRA&#199;&#195;o</Label>
            <Symbol>CalibrateIcon</Symbol>
            <Row>2</Row>
            <Col>3</Col>
        </ActionKey>
</Keys>
</Keyboard>
```

**Comment by JorgeMattos** [comment] 2019-09-28 23:04
He shakes the screen.

https://youtu.be/7N7FJn36JpE

**Comment by JorgeMattos** [comment] 2019-09-28 23:24
Something changes on the dynamic keyboard as you go to Optikey's native conversation or mouse.

**Comment by JorgeMattos** [comment] 2019-09-28 23:51
Formatted for UTF-8 The problem is when exiting the minimized native mouse.
With the native mouse maximized, not the bug.
 
In the other two dynamic keyboard not the bug because it uses dynamic mouse and not native mouse ...

https://youtu.be/-VwMGKygqVs

**Comment by AdamRoden** [comment] 2019-09-29 02:27
@JuliusSweetland @JorgeMattos Hi guys. I'm back to comment that all this fuss regarding dynamic keyboards is now entwined with the dynamic keyboard size and position enhancement I'm trying to merge. There are equal chances my code will wipe away this issue, and/or introduce new ones. My thoughts are: merge my code, retest, and then fix whatever is still not correct.

**Comment by JuliusSweetland** [comment] 2019-09-30 12:10
@AdamRoden Agreed. I have merged and created a new iteration of v2.29.0. Adam can you please supply some sample dynamic keyboards and we can all re-test to see where we are. New version is here: https://github.com/OptiKey/OptiKey/releases

**Comment by JuliusSweetland** [comment] 2019-09-30 12:26
@AdamRoden One thing which appears to be wrong is if you navigate to a new dynamic keyboard which changes the height and then right click on OptiKey and select BACK. The heigh change is not reversed to the default setting. In merging your changes I removed my calls to reset the docked size (full or collapsed), which would reinstate the previous height. What is the correct way to do this now?

**Comment by AdamRoden** [comment] 2019-09-30 12:50
@JuliusSweetland I'm guessing the dynamic keyboard you went to had the PersistNewState flag set to true.

	
	
	<PersistNewState>True</PersistNewState>

**Comment by JuliusSweetland** [comment] 2019-09-30 13:00
@AdamRoden Actually no, the keyboard is AltAlphaHorizontalKeyboard.xml which I've recently added to the bundled DynamicKeyboards folder in the Resource folder. It doesn't actually specify a height so there are two interesting things going on:

1.Why does OptiKey resize at all?
2.Why does OptiKey not revert any resize when using BACK from the right click context menu.

You can reproduce the issue simply by navigating to that keyboard ("Alt Alpha Horizontal EN"), observing the resize, and then right click and select BACK and observe no reversion to the original size.

**Comment by JuliusSweetland** [comment] 2019-09-30 13:01
@JorgeMattos FYI the new dynamic keyboards express their heights in pixels by default now. They also support percentages, but your keyboards will need to be updated to include "%" after the height number. This is only included in the 2.29.0 which has not officially been released yet.

**Comment by AdamRoden** [comment] 2019-09-30 13:40
> @AdamRoden Actually no, the keyboard is AltAlphaHorizontalKeyboard.xml which I've recently added to the bundled DynamicKeyboards folder in the Resource folder. It doesn't actually specify a height so there are two interesting things going on:
> 
> 1.Why does OptiKey resize at all?
> 2.Why does OptiKey not revert any resize when using BACK from the right click context menu.
> 
> You can reproduce the issue simply by navigating to that keyboard ("Alt Alpha Horizontal EN"), observing the resize, and then right click and select BACK and observe no reversion to the original size.

I'm not getting the same behavior as you. It doesn't resize on me. Is there a size setting tucked away in the user.config that is different between us.

**Comment by JuliusSweetland** [comment] 2019-09-30 13:53
@AdamRoden Yes you are correct. After cleaning my build directories and user keyboard folders I cannot replicate this problem. Please ignore.

**Comment by JuliusSweetland** [comment] 2019-09-30 14:00
@AdamRoden Although, if you add this to the AltAlphaHorizontalKeyboard.xml it does break in the way I describe, i.e. it resizes and then BACK from the context menu does NOT undo the new size:
<Height>25%</Height>

**Comment by JorgeMattos** [comment] 2019-09-30 14:40
@JuliusSweetland @AdamRoden Is Optikey's native keyboard height PX or %?

Another behavior I noticed is restart in context is not the same as restart when changing the time of a key.
But this is a matter for another tropic.
Just said because the last changes made are not saved with restart in context.

**Comment by JuliusSweetland** [comment] 2019-09-30 14:51
@JorgeMattos Natively we store heights in pixels, but I believe this new change is correct. We should, on dynamic keyboards, be accepting height expressed as numbers as pixels, and expressed as "50%" (for example) as percentages.

I cannot replicate your other issue. If I QUIT or RESTART OptiKey from the context menu then I see this in my logs, indicating that my settings have been saved: "PERSISTING USER SETTINGS AND SHUTTING DOWN"

Could you please let me know some more details, or the steps to reproduce the problem.

**Comment by JorgeMattos** [comment] 2019-09-30 16:18
Actually using "%" does not change the height value of Optikey.
Just the screen that shakes a noise.
But the other problem has returned, does not accept dynamics below 50%.

Version 2.23.0 is more stable for dynamic keyboards.

```
<Keyboard>
    <Name>Mouse</Name>
    <HideFromKeyboardMenu>True</HideFromKeyboardMenu>
    <Height>8%</Height>
    <SymbolMargin>5</SymbolMargin>
    <BorderThickness>1,1,1,1</BorderThickness>
    <Grid>
        <Rows>1</Rows>
        <Cols>10</Cols>
    </Grid>
```

**Comment by JuliusSweetland** [comment] 2019-09-30 16:44
Hi @JorgeMattos Actually I believe you are seeing that 8 interpreted as 8 pixels. When we try to size OptiKey to a dock 8 pixels high Windows will attempt this and then forcibly resize OptiKey to the original size. That's where the flicker/stutter/shake you see is coming from.

**Comment by JorgeMattos** [comment] 2019-09-30 16:54
@JuliusSweetland that's true...

**Comment by JorgeMattos** [comment] 2019-09-30 16:55
@JuliusSweetland  Truth...

**Comment by JuliusSweetland** [comment] 2019-09-30 18:00
Thanks Adam. Let me know if I can help at all...

**Comment by JuliusSweetland** [comment] 2019-10-03 21:00
@AdamRoden @JorgeMattos Ok, with Adam's latest PR (thank you!) and a few minor fixes we have a new pre-release version for testing: v2.30.0

1. Could you please both test this and let me know if it fixes existing issues. Direct download here: https://github.com/OptiKey/OptiKey/releases/download/v2.30.0/OptiKeySetup-2.30.0.exe
2. @AdamRoden Do you have any dynamic keyboards that I can bundle with OptiKey to show how some of these new settings should be used?
3. @AdamRoden Is there any chance you could help me add some details to the wiki page? https://github.com/OptiKey/OptiKey/wiki/Creating-and-Using-Dynamic-Keyboards

**Comment by AdamRoden** [comment] 2019-10-03 21:47
@JuliusSweetland Will do. For now here are some notes and sample keyboards. If you want more detail just give me some time and I can put something nicer together.
[Comments and Samples.zip](https://github.com/OptiKey/OptiKey/files/3688189/Comments.and.Samples.zip)

**Comment by JuliusSweetland** [comment] 2019-10-03 22:00
Great thanks. I'll check it all out tomorrow

**Comment by JuliusSweetland** [comment] 2019-10-04 11:18
@AdamRoden Example keyboards look great. I've updated the v2.30.0 release to include those keyboards

**Comment by JuliusSweetland** [comment] 2019-10-04 11:20
@AdamRoden @JorgeMattos Thanks all!

**Closed** 2019-10-04 11:19 UTC

**Comment by JuliusSweetland** [comment] 2019-10-04 11:30
@AdamRoden FYI I've updated the wiki here: https://github.com/OptiKey/OptiKey/wiki/Creating-and-Using-Dynamic-Keyboards

Any comments/corrections please let me know.

**Comment by JorgeMattos** [comment] 2019-10-04 11:38
> @AdamRoden @JorgeMattos Ok, com o mais recente PR de Adam (obrigado!) E algumas pequenas correções, temos uma nova versão de pré-lançamento para teste: v2.30.0
> 
> 1. Você poderia testar isso e me informar se ele corrige os problemas existentes. Download direto aqui: https://github.com/OptiKey/OptiKey/releases/download/v2.30.0/OptiKeySetup-2.30.0.exe
> 2. @AdamRoden Você tem teclados dinâmicos que posso agrupar com o OptiKey para mostrar como algumas dessas novas configurações devem ser usadas?
> 3. @AdamRoden Existe alguma chance de você me ajudar a adicionar alguns detalhes à página da wiki? https://github.com/OptiKey/OptiKey/wiki/Creating-and-Using-Dynamic-Keyboards

I'm a little confused, I don't know what to say.
Resolved the problem of shaking the screen.
But when I get out of screen conversion behavior is weirdYesterday I got stuck for an hour on a screen, not even Microsoft Windows eye worked!
I'm going to start using the lab to do the tests.
 I will read the document and create as intrusion.

 Many thanks Julius Sweetland

**Comment by AdamRoden** [comment] 2019-10-04 13:12
@JorgeMattos I'm very sorry to hear you got stuck. Nothing in any of my testing during development resulted in other eye tracking not working. If this can be reproduced it is top priority.

**Comment by JuliusSweetland** [comment] 2019-10-04 13:31
I also cannot reproduce this issue.

**Comment by JorgeMattos** [comment] 2019-10-04 13:59
@AdamRoden @JuliusSweetland   I'm sorry
I got stuck because I accidentally entered the side keyboard.
I am writing according to the tutorial.

A translator will help me on the Site, I really want to pass it all to Portuguese.

Thank you, thank you, thank you! Because there are people like you ...

**Comment by AdamRoden** [comment] 2019-10-04 14:31
@JorgeMattos You getting stuck is my fault. I intentionally left it possible for a keyboard to be positioned outside of the screen boundaries thinking it would be a cool feature to offset the keyboard and have off screen actions. The problem is, there's no fail safe. With dynamic keyboards we expose many opportunities to break things. @JuliusSweetland and I were thinking of additional checks to avoid dead end situations, they just don't exist at this time.

**Comment by JuliusSweetland** [comment] 2019-10-04 14:34
@AdamRoden which keyboard renders off screen? I should probably correct
that if it's one of the bundled example ones.

**Comment by AdamRoden** [comment] 2019-10-04 14:48
@JuliusSweetland It shouldn't be an issue with the files I put in the v2 attachment last night. But I think my original FloatRight could render off screen if you didn't have enough pixels.

**Comment by JuliusSweetland** [comment] 2019-10-04 14:54
Good news. Thanks!

**Comment by JorgeMattos** [comment] 2019-10-04 14:54
Before I had to change position in Optikey, now with these new codes do not need.
I was using the old codes, I think now it will.

```
<Keyboard>
   <Name>Big Hacker Keyboard</Name>
   <HideFromKeyboardMenu>False</HideFromKeyboardMenu>
   <ShowOutputPanel>False</ShowOutputPanel>
   <Height>32</Height>
   <SymbolMargin>10</SymbolMargin>
   <BorderThickness>1,1,1,1</BorderThickness>
   <PersistNewState>True</PersistNewState> <!--PersistNewState: if true this keyboard's state, size, and position settings will become the default values to carry forward when changing keyboards if element is not included or not true this keyboard's settings are only applicable once, and will not carry forward-->
   <WindowState>Floating</WindowState> <!--WindowState: Floating, Docked - if element is not included or does not contain a value from the list then use the saved default value-->
   <DockSize>Full</DockSize> <!--DockSize: Full, Collapsed - if element is not included or does not contain a value from the list then use the saved default value. If window is floating this will be ignored-->
   <Position>TopLeft</Position> <!--Position: TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight - if element is not included or does not contain a value from the list then use the saved default value-->
   <Width>-300</Width> <!--Width and Height: -9999 to 9999. % implies percent of screen. if negative then use the sum of the value and the screen's dimension - i.e. if a Width of -300 is sent and the screen is 1920 wide then the keyboard width will be set to 1620 by way of ((-300) + (1920) = (1620))-->
   <Height>40%</Height>  
   <HorizontalOffset>50%</HorizontalOffset> <!--Horizontal and Vertical Offset: -9999 to 9999. % implies percent of screen. if negative then offset left or up-->
   <VerticalOffset>50%</VerticalOffset>  
   <Grid>
      <Rows>7</Rows>
      <Cols>12</Cols>
   </Grid>
   <Keys>
   <!-- ... Individual Key Definitions Go Here ... -->
   </Keys>
</Keyboard>
```

**Comment by JuliusSweetland** [comment] 2019-10-04 15:08
Don't forget to change that Height property. 32 is now 32 pixels. You'd
need "32%" for the old sizing.

**Comment by JorgeMattos** [comment] 2019-10-06 15:41
@JuliusSweetland @AdamRoden 
Congratulations Julius Sweetland and @AdamRoden, great new features, thank you so much for your work. We ALS patients thank you.

**Comment by JuliusSweetland** [comment] 2019-10-06 16:04
It's all Adam. Thanks Adam!
