### ISSUE TITLE
Just "YES" or "NO"

### ISSUE THREAD

**Issue by robertorigotto** [OptiKey/OptiKey#322] opened 2017-05-13 12:29 UTC
Please help me !!!

My father needs to try OptiKey with Tobii Eyex...
...but I am sure that the "Conversation" mode is too much information for him at this moment.

So, I would like to start with him using just 2 possibilities / answers at screen: "YES" or "NO"

Example:
I would ask: "Father, are you feeling okay ?" 
He would look at the "YES" or "NO" imagem and select it.

Is it possible or could you help me how to do that ?

Regards,
Roberto

**Comment by alexandre-mbm** [comment] 2017-05-13 13:55
@JuliusSweetland, this also would be good to go without bigger calibration.

@robertorigotto, why you think so? My father also is a person with ALS. If you do not want give us details here, you can yet contact me by e-mail: alexandre.mbm@gmail.com

**Comment by zelmon64** [comment] 2017-05-15 13:42
@robertorigotto I was curious about this so I had a go at making a secondary conversation keyboard and this is the result:

![image](https://cloud.githubusercontent.com/assets/15001389/26059898/3981a548-397b-11e7-9845-3dc6dfd58942.png)

It is accessed by pressing the Y/N key in the bottom left corner of the normal conversation keyboard. 

![image](https://cloud.githubusercontent.com/assets/15001389/26060301/7fd35cfc-397c-11e7-98ea-c516b5b5bee2.png)

It's currently only in English but it can easily be expanded to the other supported languages. When Yes or No is pressed that word is spoken and entered on the scratchpad so that you can see what was last said.

https://drive.google.com/open?id=0B7SYYOqNW4FSaURSMVZnMzJreDg

**Comment by zelmon64** [comment] 2017-05-15 14:11
@robertorigotto I was wondering whether the scratchpad was actually useful or not so I've done another build without it:

https://drive.google.com/open?id=0B7SYYOqNW4FSMVNHSi1HcUEwb2s

![image](https://cloud.githubusercontent.com/assets/15001389/26061730/9fb2b6f4-3980-11e7-9cbc-463f024b2e74.png)

**Comment by alexandre-mbm** [comment] 2017-05-15 15:08
@zelmon64, thank your very much by your example.

**Comment by zelmon64** [comment] 2017-05-15 19:28
@alexandre-mbm I'm glad you like it. I've added French and German (because they're the ones I'm most confident on how to say yes/no in) examples to make it easy to add the other languages. I've used the tick and cross as the default but kept the YES and NO for the UK English because I thought it was nicer.

![image](https://cloud.githubusercontent.com/assets/15001389/26074788/0af08a3e-39ab-11e7-8734-3d19f1d6bc84.png)

When adding the other languages I realised they don't all have free spaces on the ConversationAlpha keyboard so I added a button to the bottom left corner of the ConversationNumericAndSymbols keyboard. I don't yet know how the icons are done so it's just a Y/N at the moment but it would be nice to have a tick/cross icon.

![image](https://cloud.githubusercontent.com/assets/15001389/26074765/f1784f06-39aa-11e7-9046-6a5f2515f502.png)

b63f5636417496fc239bac8bfd17d3fd0744ff90

https://drive.google.com/open?id=0B7SYYOqNW4FSOTJOOHQwcHRFREE

**Comment by JuliusSweetland** [comment] 2017-05-15 19:30
Really nice work William. There should be a resource for yes and one for no
which will automatically translate as the user changes languages.

**Comment by robertorigotto** [comment] 2017-05-15 20:34
@zelmon64 and @alexandre-mbm thank you VERY VERY MUCH ! That´s EXACTLY what I want !
You are doing a great job and helping a lot of people around the world !

**Comment by alexandre-mbm** [comment] 2017-05-15 20:42
@robertorigotto, I did none. All was @zelmon64.

@zelmon64,
> I've used the tick and cross as the default

Hint: decrease the size of "x" for more proportion.

**Comment by alexandre-mbm** [comment] 2017-05-15 20:45
> When adding the other languages I realised they don't all have free spaces on the ConversationAlpha keyboard

@JuliusSweetland, would be interesting to possibility to config these spaces. Another issue...

**Comment by JuliusSweetland** [comment] 2017-05-15 20:47
There is work under way to let users create their own keyboards, which
might give you what you want.

**Comment by alexandre-mbm** [comment] 2017-05-15 21:15
@JuliusSweetland, is there an open issue?

Would be interestind the virtual keys triggering executables (scripts) or AutoHotKey's macros.

**Comment by zelmon64** [comment] 2017-05-15 21:37
@JuliusSweetland Thanks for the tip. I'm trying to use `Resources.YES` and `Resources.NO` but they're only coming up as English. It's the same for the YesNoQuestion quitting keyboard so I'm not sure what the problem is. I'm guessing the information is stored in the `OptiKey.resources.dll` files in the folders such as `es-ES`. Those files are around 40 KB each. 

I also have version 2.3.15.0 installed and the other languages don't appear with that either. Are there separate language packs that need to be downloaded/installed?

**Comment by JuliusSweetland** [comment] 2017-05-16 05:57
You need to change langue from the languages keyboard. Run OptiKey,
navigate to the main menu, navigate to languages, and select one.
Everything should now be in the selected language.

**Comment by zelmon64** [comment] 2017-05-16 06:58
@JuliusSweetland unfortunately that's what I was doing. All the keyboard layouts changed but all the words remained in English. Are there any logs I can look at / post?

**Comment by JuliusSweetland** [comment] 2017-05-16 07:01
Oh sorry I was being an idiot. There are two language settings; one can be
changed from the menu and changes the keyboard layouts. The other can only
be changed from the Visual tab of the Management Console (ALT+M) and
changes the UI language. Try changing the other setting. Apologies.

**Comment by zelmon64** [comment] 2017-05-16 07:16
Thanks @JuliusSweetland, that did that trick! Should maybe the language setting on the main menu be used to change both settings so then the Management Console could be used for individual adjustments?

**Comment by JuliusSweetland** [comment] 2017-05-16 07:26
I decided against that as the user's language won't change whilst using
OptiKey, only the language they want to type in.

**Comment by zelmon64** [comment] 2017-05-16 07:38
@JuliusSweetland that makes sense thanks. 

I also manages to combine the tick and cross icons into one  which I think looks alright:

![image](https://cloud.githubusercontent.com/assets/15001389/26094417/d5109604-3a11-11e7-88a6-7012db1d2623.png)

https://drive.google.com/open?id=0B7SYYOqNW4FSMXpxT2F6M2M5Z0U

**Comment by zelmon64** [comment] 2017-05-16 11:57
https://drive.google.com/open?id=0B7SYYOqNW4FSZnR0eFlOcFpsWFE

I realised the back button is supposed to take you to the main menu so I took out the menu button and added buttons to go to the Alpha and Sym/Num keyboards instead:

![image](https://cloud.githubusercontent.com/assets/15001389/26104608/80604616-3a36-11e7-88f5-8ced8881dfa0.png)

@alexandre-mbm I'm not sure what to do about the size difference between the tick and the cross because they're currently automatically sized to fill their buttons. I can't seem to find an option for precise sizing adjustments.

**Comment by alexandre-mbm** [comment] 2017-05-16 13:15
> I can't seem to find an option for precise sizing adjustments.

@zelmon64, if they are images, you can change them.

**Comment by JuliusSweetland** [comment] 2017-05-16 13:18
They're Paths which are sized automatically. The reason they aren't sizing
equally is because the tick is not the same size horizontally and
vertically. It's actually very tricky to design a keyboard which scales
automatically, but one thing you can try is to set the WidthSpan and
HeightSpan on the keys to 2 (or even 3). This won't change the scaling, but
it will result in smaller images, which might look more balanced.

**Comment by alexandre-mbm** [comment] 2017-05-16 13:22
![yes-no-proportion](https://cloud.githubusercontent.com/assets/957501/26108001/8af1355a-3a21-11e7-93f3-b26a76a8b559.png)

**Comment by zelmon64** [comment] 2017-05-16 13:38
@alexandre-mbm for reference here's where it's defined:
https://github.com/zelmon64/OptiKey/blob/4513a10d3f234d28458f06ae1df0e12d65c22a10/src/JuliusSweetland.OptiKey/Resources/Icons/KeySymbols.xaml#L65
I was lucky with making the new tick/cross icon because I simply copied the parts together.

@JuliusSweetland thanks for the information.

What do you guys think about this? I used 1.5 on the tick and 2 on the cross:

![image](https://cloud.githubusercontent.com/assets/15001389/26108410/5b3c0a60-3a44-11e7-923e-85ae44a05e7e.png)

**Comment by JuliusSweetland** [comment] 2017-05-16 13:39
Looks good to me!

**Comment by zelmon64** [comment] 2017-05-16 13:49
![image](https://cloud.githubusercontent.com/assets/15001389/26109249/d9a4fe3c-3a46-11e7-8a42-af51a944f796.png)

**Comment by alexandre-mbm** [comment] 2017-05-16 13:52
In this last the words are small and with different sizes. :-1:

**Comment by zelmon64** [comment] 2017-05-16 14:02
If I remove `SharedSizeGroup="KeyWithSymbol"` this is what I get. I think the YES is slightly bigger.

![image](https://cloud.githubusercontent.com/assets/15001389/26109803/47e78378-3a48-11e7-9b55-fd4ab35122de.png)

**Comment by zelmon64** [comment] 2017-07-07 14:28
@JuliusSweetland and @alexandre-mbm could I please have some feedback on the last font sizes and on whether it's okay to simply remove `SharedSizeGroup="KeyWithSymbol"`? If it's all okay I'll make a PR for it so that this can be closed.

**Comment by JuliusSweetland** [comment] 2017-07-07 14:38
@zelmon64 If the font sizes are a concern then it is possible to not show the text at all and rely on symbols? That would allow you to use the width/height span method?

RE: Removing the shared size group - yes you can do this. It is intended to group sets of similar keys together so that they scale uniformly. In this instance you could opt out and let each key size itself independently. How does it look if you do this?

How is this keyboard going to be available? I saw from an earlier screenshot that you have added a link from the conversation keyboard. Perhaps the yes/no keyboard should stand on it's own. There is a setting to determine the starting keyboard. I am guessing that the main use case is for people who would struggle to use smaller keys or more complicated keyboards. If so then maybe YES, NO, Sleep is all that is needed (i.e. no ABC, 123, or back keys)? Completely up to you though.

**Comment by zelmon64** [comment] 2017-07-07 14:58
@JuliusSweetland The last picture is with the `SharedSizeGroup="KeyWithSymbol"` removed for the Yes and No button. I thought it looks alright but since it didn't get any feedback I wasn't sure.

That makes sense to make it a more separate keyboard. I'm just wondering since you said user defined keyboards are on the way, is it still a good idea to add this in?

**Comment by JuliusSweetland** [comment] 2017-07-07 16:15
@zelmon64 If it's ready to go then sure, we can always refactor later when user defined keyboards arrive.

**Comment by zelmon64** [comment] 2017-07-07 16:52
@JuliusSweetland okay, I think I'll have a go at making it an option as a starting keyboard (and possibly also still keep it as an addon to the conversation keyboard) then make a PR if it goes well. Thanks for your input :).

**Comment by JuliusSweetland** [comment] 2017-07-07 16:55
Could you add a setting to display the key on the conversation keyboards so
it can be optionally enabled? That would make the change invisible to
existing users.

**Comment by zelmon64** [comment] 2017-07-07 16:57
@JuliusSweetland ooh that's a good idea. Yes I'll do that.

**Comment by zelmon64** [comment] 2017-07-07 22:17
![image](https://user-images.githubusercontent.com/15001389/27978837-d0578f7e-6369-11e7-9ed1-b4aae6a9fd63.png)
I decided to hide the ABC and 123 keys but keep the quit and calibrate keys when in the Y/N keyboard only mode.

Here's a build and I'll make that PR:
https://drive.google.com/open?id=0B7SYYOqNW4FSdDFfX29SWVdfWkU

**Comment by JuliusSweetland** [comment] 2017-07-08 21:44
Closing as the new keyboard is merged and will be included in the next release.

**Closed by JuliusSweetland** 2017-07-08 21:44 UTC
Labels: STATUS:help wanted, STATUS:in progress, TYPE:improvement

**Comment by alexandre-mbm** [comment] 2021-02-18 01:40
Is this feature on some release currently?

In positive case, what is the step by step to activate it?

**Comment by JuliusSweetland** [comment] 2021-02-18 12:23
@alexandre-mbm Yes this was deployed. If you go to management console, visuals and then enable these two settings:
![image](https://user-images.githubusercontent.com/4722561/108356522-26100b80-71e4-11eb-8219-cfb9aa0a158d.png)
