### ISSUE TITLE
ALT-M Crash on Windows 11 Home

### ISSUE THREAD

**Issue by marcstein** [OptiKey/OptiKey#858] opened 2022-08-27 15:44 UTC
# Version
 - Operating system and version: Windows 11 Home
 - OptiKey version: 3.2.3
 - Computer Lenovo IdeaPad Gaming 3
 - Eye Tracker: Tobii 5

# Steps to reproduce the issue

Press ALT-M

# Any other information that helps to describe and/or reproduce the problem

This occurs even when the Tobii device is not installed.
C++ Redistributable library has been installed

# Screenshots
![Crash!](https://user-images.githubusercontent.com/804069/187037482-35959643-b4b2-436d-b066-eeeba44b7415.png)

**Comment by kmcnaught** [comment] 2022-09-01 11:35
Thank you for the report. I am attempting to upgrade a PC to Windows 11 to test, but it's taking a while!

**Comment by marcstein** [comment] 2022-09-01 13:10
Thank you!

Best,
Marc

Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. ***@***.***
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by marcstein** [comment] 2022-09-07 17:07
Hi, 
Any progress on this? Should I just try downgrading to Windows 10?

**Comment by AdamRoden** [comment] 2022-09-08 01:30
I've been using Optikey on a Surface Book running Windows 11 for a long time and have no issues with Alt+m. I don't think the issue is Windows. Are you using Optikey to type Alt+m, or a physical keyboard? I think you'll need to submit your Optikey log for us to investigate further.

**Comment by marcstein** [comment] 2022-09-08 18:46
Interesting. I've attached a log. The issue for me seems to be using the TobiiEyeTracker5 under Windows 11 (but not Windows 10). The same tracker works with Windows 10 fine, with no crashes.

[OptiKeyPro.log](https://github.com/OptiKey/OptiKey/files/9529788/OptiKeyPro.log)

**Comment by AdamRoden** [comment] 2022-09-08 19:54
All that log shows is you opening Optikey and then closing it a few seconds later. It doesn't show any activity.

**Comment by marcstein** [comment] 2022-09-08 21:35
Here's a longer log that shows the exception that causes the crash.

[OptiKeyPro-1.log](https://github.com/OptiKey/OptiKey/files/9530743/OptiKeyPro-1.log)

**Comment by AdamRoden** [comment] 2022-09-08 22:01
That is more informative. The app seems to be throwing an exception when trying to load "Roboto" font with a "Condensed" font stretch. Perhaps you need to reinstall the Roboto font or modify your config to use one of the other fonts.

**Comment by marcstein** [comment] 2022-09-08 22:04
Is there a way to edit the config manually? A text config file?

Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. ***@***.***
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by AdamRoden** [comment] 2022-09-08 22:36
The file is at some path like this: C:\Users\adamr\AppData\Roaming\Optikey\OptikeyPro.exe_Url_pqculjajaftnm00q0xsd50ifmheytajf\3.2.3.0

You can edit it with notepad. Try replacing "Condensed" with "Normal" then test and send a new log file. I'm skeptical that it will fix the issue. Have you tried uninstalling and reinstalling Optikey?

**Comment by marcstein** [comment] 2022-09-08 23:27
Thanks! The combination of fixes worked. I uninstalled OptiKey, reinstalled Roboto,  and reinstalled Optikey in that order. That worked! I did find the user.config but it doesn't seem to contain the font settings. But I was able to access the management console in the new install.

Many thanks for your patience!

Best,
Marc

**Comment by alexandre-mbm** [comment] 2022-09-13 02:59
> Here's a longer log that shows the exception that causes the crash.
> 
> [OptiKeyPro-1.log](https://github.com/OptiKey/OptiKey/files/9530743/OptiKeyPro-1.log)

We can analize from here:

```log
2022-09-08 17:27:36,817 [ 1] INFO  JuliusSweetland.OptiKey.UI.Windows.MainWindow: RequestManagementWindow called.
2022-09-08 17:27:36,817 [ 1] INFO  JuliusSweetland.OptiKey.UI.Windows.MainWindow: Releasing modifiers (shift:Up, ctrl:Up, win:Up, alt:Up)
2022-09-08 17:27:37,051 [ 1] ERROR JuliusSweetland.OptiKey.OptiKeyApp: A DispatcherUnhandledException has been encountered...
System.ArgumentException: Requested value '"Condensed"' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at JuliusSweetland.OptiKey.UI.ViewModels.Management.VisualsViewModel.Load() in C:\dev\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\ViewModels\Management\VisualsViewModel.cs:line 638
   at JuliusSweetland.OptiKey.UI.ViewModels.ManagementViewModel..ctor(IAudioService audioService, IDictionaryService dictionaryService, IWindowManipulationService windowManipulationService) in C:\dev\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\ViewModels\ManagementViewModel.cs:line 36
   at JuliusSweetland.OptiKey.UI.TriggerActions.OpenManagementWindowAction.Invoke(Object parameter) in C:\dev\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\TriggerActions\OpenManagementWindowAction.cs:line 36
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.Interactivity.EventTriggerBase.OnEvent(EventArgs eventArgs)
   at System.Windows.Interactivity.EventTriggerBase.OnEventImpl(Object sender, EventArgs eventArgs)
   at Prism.Interactivity.InteractionRequest.InteractionRequest`1.Raise(T context, Action`1 callback)
   at JuliusSweetland.OptiKey.UI.Windows.MainWindow.RequestManagementWindow() in C:\dev\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\Windows\MainWindow.xaml.cs:line 179
   at Prism.Commands.DelegateCommand.Execute()
   at Prism.Commands.DelegateCommand.Execute(Object parameter)
   at Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Before this the user was trying to type something in the keyboard of screen.

**Closed** 2022-09-15 15:17 UTC

**Comment by kmcnaught** [comment] 2022-11-17 10:09
This isn't what I thought it was. The error happens when the `VisualsViewModel` tries to parse the `FontStretch` setting. There is a bug in the installer that sets the value to `"Condensed"` (including quotes) instead of `Condensed`. 

Easy fix - make sure these actions don't have any superfluous double quotes. I've fixed on a fork, will fix in Optikey master also

![image](https://user-images.githubusercontent.com/12151404/202418139-2a97814f-ed11-4730-beb9-a475cbc35d91.png)
