### ISSUE TITLE
Degrading performance over time = memory leak?

### ISSUE THREAD

**Issue by Sheeva007** [OptiKey/OptiKey#430] opened 2018-02-01 19:41 UTC
@JuliusSweetland  i don't like to do that but,Let's speak about bugs. Like pdeclerc wrote i use OptiKey 24/7 on a microsoft surface I7 16 gb of ram. Not too bad for running OptiKey :-)
I remark OptiKey after few hours coming slower and slower. To fixe that i have to reboot, very comon under windows. But quitting and restarting OptiKey it's not a solution. For users it's looking like a real keybord key's glued.
Next. After a while following a fresh installation, OptiKey loose focus. I mean all windows elements come in front of OptiKey , including start menu where pointer stay under the start menu or every Windows elements. :-(
That's all for today. my key coming to glue.
Dominique.

**Comment by JuliusSweetland** [comment] 2018-02-01 19:44
Hi Dominique. What do you mean when you say "But quitting and restarting
OptiKey it's not a solution”? If you use Task Manager to kill the OptiKey
process and then start OptiKey again is it faster again?

Could you send me a screenshot when other windows start to cover OptiKey?
This shouldn't be possible.

Thanks.

**Comment by Sheeva007** [comment] 2018-02-02 14:59
@JuliusSweetland I will try.

**Comment by maartee** [comment] 2018-02-08 17:10
Dominique,
looks like this issue is similar to #382, you may try monitoring RAM usage using Task manager.

**Comment by Sheeva007** [comment] 2018-02-09 11:13
@maartee i will try that and i come back to you. thx.

**Comment by Sheeva007** [comment] 2018-02-13 19:27
@maartee effectively when i close others apps optikey run again smoothly.
is not a solution . but not a priority.  thx.

**Comment by JuliusSweetland** [comment] 2018-02-13 19:29
That sounds like your computer may be running low on memory. When you
choose other apps your free memory that OptiKey can use.

**Comment by JuliusSweetland** [comment] 2018-02-14 11:37
@maartee Hi Martin - this issue has been raised on and off for a while now, but it seems to affect some people and not others. Is there any chance that you would like to look into a potential memory leak? If so I could give you a license for JetBrains toolbox, which includes ReSharper, dotMemory, and dotTrace (as well as a bunch of other programs) valid for a year (possibly longer)?

**Comment by Sheeva007** [comment] 2018-02-14 20:39
@JuliusSweetland @maartee so, here is  a screenshot. optikey memory eater.
![otikey_mem](https://user-images.githubusercontent.com/16621041/36226862-5dd120d6-11cf-11e8-8d28-7d25414e48eb.jpg)

**Comment by JuliusSweetland** [comment] 2018-02-15 14:28
![memory leak investigation 1](https://user-images.githubusercontent.com/4722561/36261359-fe3d222c-125b-11e8-8ee3-6aefd407c32e.PNG)

Looks like the memory leak was caused by the most innocuous of things - the attached behaviour responsible for moving the caret (flashing cursor in the text box at the top) wasn't cleaning up after itself properly, resulting in every key in every keyboard being retained. There may be other small leaks, but this is the main leak and it will be fixed in the next release 2.0.14.

**Comment by JuliusSweetland** [comment] 2018-02-15 14:45
Looks a bit better:
![image](https://user-images.githubusercontent.com/4722561/36262289-e795affa-125e-11e8-8030-5a4168ccce2a.png)

**Comment by JuliusSweetland** [comment] 2018-02-16 13:01
A new pre-release of OptiKey is available as version 2.0.14 which includes the memory leak fix: https://github.com/OptiKey/OptiKey/releases

Could you please try it out and let me know how it works for you.

N.B. I have signed the installer and OptiKey.exe file with a new certificate, so please don't worry if Windows warns you of an untrusted certificate - it takes time for trust to build up again.

**Comment by maartee** [comment] 2018-02-16 15:17
Hi Julius,  after half an hour of intensive usage, I can say that helped significantly. However, I will continue testing. Memory keeps around 70MB steadily.

**Comment by JuliusSweetland** [comment] 2018-02-16 15:20
@maartee Excellent, thanks Martin. This has been bugging me for a LONG time. I'm very glad a fix is on the way for everyone.

I've got another change being readied by a contributor which will need a bit of testing and then I'm ready to release.

Out of interest did you receive any warnings when installing or running that pre-release of OptiKey? It's signed with a new certificate which Windows will probably consider to be untrusted for a little while. I don't see the warnings as I have the certificate installed locally so my system trusts it.

**Comment by maartee** [comment] 2018-02-17 18:32
Yes, I received the 'untrusted' warning from Windows Defender when installing. 

Regarding the memory leak issue, I can confirm again that Optikey with fix is working smoothly for me,  RAM usage stabilized. No more degraded performance. Great!

**Comment by JuliusSweetland** [comment] 2018-02-17 20:18
That's excellent. Thank you! The next release of OptiKey is looking really
strong.

**Comment by Sheeva007** [comment] 2018-02-17 21:41
@JuliusSweetland @maartee i try optikey 2.0.14 t'ill this morning. no memory leak anymore.
thanks guy's

**Closed** 2018-03-03 19:30 UTC
Labels: STATUS:in progress, TYPE:bug
