### ISSUE TITLE
Management console dropdowns not fully visible in v2.11.0 pre release

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#403] opened 2017-10-16 18:36 UTC
I installed  v2.11.0_pre-release_8 and ran it. My settings have OptiKey docked at the top of the screen. When I launch the management console it appears at the bottom of the screen (in the remaining space). If I try to change the point source, the dropdown box opens upwards and the top few items are hidden behind Optikey. This only happens with the installed program, not when I run the same version from Visual Studio.

**Comment by kmcnaught** [comment] 2017-10-16 19:13
![img_20171016_192623940](https://user-images.githubusercontent.com/12151404/31630378-53e63d48-b2ae-11e7-812e-f64ac2cadcce.jpg)

Attached photo of my screen because I don't can't take a screenshot without the focus coming off OptiKey...

**Comment by JuliusSweetland** [comment] 2017-10-16 19:39
This can be replicated by enlarging OptiKey (using the size and position keyboard) until it covers a little more than half of the screen (in docked mode).

**Comment by bswearingen** [comment] 2017-10-17 19:49
I can take a try at fixing this if no one else has started on it

**Comment by JuliusSweetland** [comment] 2017-10-17 19:52
Great thanks Ben. The problem (I think) is caused by the combo boxes having
no idea to the is a window with uiaccess (OptiKey, meaning it hovers above
EVERYTHING) covering part of where it wants to draw the combo box items.

I'm not really sure anything could be done about this, but I wish you good
luck!

**Comment by bswearingen** [comment] 2017-10-18 22:18
That sounds right, especially with it not happening in when debugging.

It happens whenever a combobox drops down (or up in the original case) into OptiKey, which means that it happens quite a lot if OptiKey is docked at the bottom of the screen.

![combobox_blocked](https://user-images.githubusercontent.com/16676113/31744846-851f11f6-b42e-11e7-94f6-c2a98def03ab.png)

I'm going to spend some more time thinking of a fix and figuring out the actual implementation, but right now I'm thinking that the combobox popups shouldn't be extending outside the management window itself.

**Comment by Chopinsky** [comment] 2017-10-18 23:10
Could we make the settings console floating above the OptiKey instead, or temporarily suspending OptiKey's UI blocking feature? I've always struggled with using the settings console if OptiKey takes more than half of the screen.

**Comment by zelmon64** [comment] 2017-10-18 23:23
How about automatically minimising OptiKey when the console opens and restore it again when it closes?

**Comment by bswearingen** [comment] 2017-10-18 23:50
@Chopinsky that definitely sounds like a possibility, but I haven't done much development with UIAccess apps. I'll look into that tomorrow night.

@zelmon64 Another option, and would likely be the easiest to implement. In my brief experience with OptiKey, minimizing seems to drop all functionality until it's restored. It could just be me not understanding minimized mode, but if I'm understanding it correctly we would be locking out users with motor limitations from changing management settings.

**Comment by zelmon64** [comment] 2017-10-19 13:55
@bswearingen I thought I read somewhere that OptiKey can't be used to interact with the management console but I have never tried to. It could instead switch to the collapsed mouse keyboard.

**Comment by JuliusSweetland** [comment] 2017-10-19 13:56
No you should be able to change settings in the Management Console using
OptiKey itself.

**Comment by bswearingen** [comment] 2017-10-19 22:10
I've been attempting to get this replicated in debug so that I can actually test a potential fix. 

[The documentation for Topmost](https://msdn.microsoft.com/en-us/library/system.windows.window.topmost(v=vs.110).aspx) has a sentence on how multiple windows with Topmost are handled. From the sounds of it, each individual window with Topmost will still appear above those without Topmost, and the currently active window will appear above all other Topmost windows. In the situation that's causing this bug, the command window is being opened non-modally, which means that it isn't being set to Topmost. So, adding:

`childWindow.Topmost = true;`

might be enough to stop the combo box from getting drawn over. The big issue is that it's not happening in dev, even with a signed package with uiAccess = true in the manifest, so I can't actually test that functionality.

**Comment by JuliusSweetland** [comment] 2017-10-19 23:47
UiAccess also requires that the app runs from a trusted location, which
essentially means somewhere in Program Files. You can check if it's working
by testing is the start menu is drawn over or under OptiKey (with UiAccess
working directly OptiKey should display over the start menu).

**Comment by bswearingen** [comment] 2017-10-19 23:57
Thanks! I'll give that a try tomorrow night.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by bswearingen** [comment] 2017-11-01 00:49
Update: I haven't been able to get this working. I'm going to keep trying, but this bug could probably use someone else looking at it while I try to figure out what I'm doing wrong. If anyone has a basic step-by-step guide on how to get OptiKey running with all the rights the installed version has, or has the time and energy to create one, I'd greatly appreciate it. If not, hopefully I'll be able to create one eventually.

The next two weeks are going to be a bit busy for me, so unless I have an unexpected break through it might be a while before I can do that.

**Comment by JuliusSweetland** [comment] 2017-11-01 09:09
@bswearingen Not a problem. This is a very tricky problem. The only possible solution I can think of is to make the Management Console be the topmost window (over OptiKey), possibly by setting the parent as OptiKey and making it modal (or something along those lines). The problem then is that the Management Console can cover OptiKey, making it difficult/impossible for the user to continue (some users make changes to the Management Console using OptiKey itself, i.e. using mouse and keyboard simulation).

I am thinking it may be sufficient to advise users that there is a potential problem when using the Management Console when OptiKey is docked and taking up a large proportion of the screen. It is still possible to resize/move/float OptiKey and work around the Management Console that way.

**Comment by JuliusSweetland** [comment] 2017-11-18 08:09
As this can be solved by resizing/moving OptiKey, which is already supported, and no obvious solution is evident, I will close this

**Closed by JuliusSweetland** 2017-11-18 08:09 UTC
Labels: STATUS:help wanted, TYPE:bug
