### ISSUE TITLE
Mouse cursor gets "stuck" near top of screen

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#738] opened 2020-10-14 21:15 UTC
Using version 3.1.0, if I dock the keyboard to the bottom of the screen, and then try to click on somewhere near the top, the giant cursor often gets "stuck" despite me moving my gaze to a new location. The clicks end up in the correct (new) place even if the dwell completes in the wrong (stuck) location. 

This is easy to reproduce when it's docked at the bottom and I'm looking *near* the top of the screen, moving horizontally. I haven't managed to replicate it in any other situation. 

Video:
https://www.loom.com/share/cbec1a1f9455471bbd13f2c0c035698b

**Comment by kmcnaught** [comment] 2020-10-14 21:36
I should add that I haven't managed to observe this behaviour with the magnetic cursor, so my guess is it's affecting point selection in particular.

**Comment by AdamRoden** [comment] 2020-10-14 21:44
@kmcnaught Can we assume you plan on determining the root cause submitting a fix?

**Comment by kmcnaught** [comment] 2020-10-14 22:31
This is the issue:

https://github.com/OptiKey/OptiKey/blob/ee34fb83420b9ee458a3b1563cba0a2558e3509c/src/JuliusSweetland.OptiKey.Core/UI/Controls/CursorPopup.cs#L182-L188

If your calibration is off, you may temporarily pass by slightly-offscreen coordinates while trying to shift the cursor to your target. In the process the cursor won't get dragged. 

Since this only affects the visualisation I'd propose we remove this requirement, @JuliusSweetland do you have any objections? There's a totally separate question of whether anything bad happens if the mouse action is requested off-screen, and I haven't looked into whether that can happen - but removing this check in `CursorPopup` won't make any difference to it.

**Comment by AdamRoden** [comment] 2020-10-14 22:55
@kmcnaught @JuliusSweetland Two things: 1-If I'm not using the magnifier my offscreen gaze results in a click on the screen edge. 2-If I am using the magnifier my offscreen gaze results in the zoom popup coerced onto the screen, but then no click happens because my gaze is outside the popup. It would be preferable for both situations to click at the screen's edge.

**Comment by AdamRoden** [comment] 2020-10-17 00:20
@kmcnaught @JuliusSweetland I did a PR for how I think this should be fixed. Take it or leave it. Code here.
https://github.com/OptiKey/OptiKey/commit/33d9e5319aeabb08c25f0821d31bb39c5e76d3d0

**Comment by JuliusSweetland** [comment] 2020-10-17 10:52
@AdamRoden Looks good. Merged. Thanks Adam.

**Closed by JuliusSweetland** 2020-10-17 10:52 UTC
