### ISSUE TITLE
Accented first character breaks multikey selection workflow

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#386] opened 2017-09-28 22:12 UTC
In french or spanish (I haven't checked other languages) you can select an accent for the first letter of a multi-key word, but it doesn't trigger a multi-key selection.

1- Turn on multikey selection
2 - Select accent 
3 - Select letter to apply to accent
4 - The accented letter is selected, 
5 - You don't enter multi-key mode until the second letter is typed.

Since accents are disabled in the middle of a multi-key word, it would be consistent to also disable them for the first letter, therefore bypassing this problem. The word prediction works fine in this instance (it will predict the word with the correct accents). 

Otherwise if accents are to be allowed, the state logic of "in the middle of a multikey selection" needs fixing to account for accented works.

**Comment by JuliusSweetland** [comment] 2017-09-29 08:31
This is not exactly a bug. Entering an accented letter using a dead key will only output one letter by design. If you want to use multi key selection just use the non accented letters. Once matched to a dictionary entry was accents they will be output automatically. I'm sure the logic could be changed to start a capture of necessary. Try out the way I describe and let me know what you think.

**Comment by kmcnaught** [comment] 2017-09-29 08:55
Sure, I was using it like you describe and the user experience was confusing. If the accents were disabled then it would be clear that you just ignore them for multikey selection. Otherwise if you want to write "árbol", the instinct is to type:
"´", "a" "r" "b" "o" "l"
which gives you "á" as a word followed whatever best matches "rbol".

Why was the intention for accented letters to behave differently vs non-accented letters in multikey selection? I can believe that in some languages there are common one-letter accented words like "á" for which this might be useful, but there are just as many common non-accented one-letter words like "a", so it doesn't make intuitive sense for them to behave differently...

**Comment by JuliusSweetland** [comment] 2017-09-29 10:46
The dead key behaviour just wasn't plugged into the multi key selection
logic. They could be combined...

**Comment by Chopinsky** [comment] 2017-09-29 12:53
I think we could still try to disable all the combining when MultiSelection key is down or locked, that could cause less confusion, since the expectation would still be "type a letter and enter multi-selection mode" with the MultiSelection key down or locked. 

For example, something like this would be more illustrative on what're available and what are not in MultiSelection mode:
![image](https://user-images.githubusercontent.com/5376280/31016647-269ed4d8-a4eb-11e7-81e1-9055959a5e95.png)

And we can disable more functional keys that won't help or won't be useful in the MultiSelection mode.

**Comment by kmcnaught** [comment] 2017-09-29 12:55
That looks good to me

**Comment by JuliusSweetland** [comment] 2017-09-29 13:50
I agree. The key enabled logic could be to disable letter and diacritic
keys that are not in the language specific set of characters in the
KeyValues class

**Comment by Chopinsky** [comment] 2017-09-30 14:59
Sounds good, I will start working on solution.

**Comment by JuliusSweetland** [comment] 2017-09-30 15:21
Great stuff, thanks!

**Comment by JuliusSweetland** [comment] 2017-10-03 20:18
Fixed by #387

**Closed by JuliusSweetland** 2017-10-03 20:18 UTC
Labels: TYPE:improvement
