### ISSUE TITLE
Possibility of creating a Dynamic keyboard for the conversation mod?

### ISSUE THREAD

**Issue by JorgeMattos** [OptiKey/OptiKey#536] opened 2019-01-29 21:41 UTC
Dynamic keyboard full screen?

When set (100 Height) Optikey locking in tests.

    <Keyboard>
    <Name>My Keyboard</Name>
    <IsShiftAware>True</IsShiftAware>
    <ShowOutputPanel>True</ShowOutputPanel>
    <Height>100</Height>
    <SymbolMargin>10</SymbolMargin>
    <BorderThickness>1,1,1,1</BorderThickness>
    <Grid>
        <Rows>4</Rows>
        <Cols>12</Cols>
    </Grid>
    <Keys>

**Comment by JuliusSweetland** [comment] 2019-01-30 12:37
@JorgeMattos Thanks for reporting the bug. What do you mean by locking?

**Comment by JorgeMattos** [comment] 2019-01-31 02:50
@JuliusSweetland sorry for the delay, it gets very slow and it locks for 20 seconds, when you go to the mouse or go back.
The toolbar is visible.

**Comment by JuliusSweetland** [comment] 2019-01-31 17:17
@JorgeMattos Ok I can replicate. The problem is that we are instructing Windows to allow a taskbar (OptiKey registers itself as a taskbar if docked, which it is by default) to take up 100% of the screen. This is going to cause Windows problems as this shouldn't be allowed.

I will attempt to create a fix which will allow the keyboard to be maximised, which is achieved by making the Window a fullscreen window, rather than a taskbar taking up 100%. I'll let you know if I manage to get it working...

**Comment by JorgeMattos** [comment] 2019-01-31 18:22
@JuliusSweetland I understood, I believe that it is not a bug behavior that I reported, the design of this dynamic keyboard does not have that goal of 100% of the window.
I believe that if you have a fullscrin option in xml it would be perfect for creating dynamic conversation.
All the dynamic keyboards I created worked perfectly.

**Comment by JuliusSweetland** [comment] 2019-01-31 21:20
@JorgeMattos I have pushed code to handle dynamic keyboards which attempt to use more than 95% of the screen height as it can cause Windows to hang.

@annakirkpatrick Do you have any desire to attempt to support full screen dynamic keyboards? The change would need to recognise that the keyboard height was 100% (here: https://github.com/OptiKey/OptiKey/blob/v2.23.0_pre-release-2/src/JuliusSweetland.OptiKey/UI/Controls/DynamicKeyboard.cs#L91) then identify the back button (we should also validate that there is one!), and then hook it up something like this:

`
var opacityBeforeFullscreen = mainWindowManipulationService.GetOpacity();
//SOMEHOW SET THE BACK BUTTON ACTION TO THIS:
() =>
{
    Log.Info("Restoring window size.");
    mainWindowManipulationService.Restore();
    Log.InfoFormat("Restoring window opacity to {0}", opacityBeforeFullscreen);
    mainWindowManipulationService.SetOpacity(opacityBeforeFullscreen);
    Keyboard = currentKeyboard;
};
Keyboard = //dynamic keyboard
Log.Info("Maximising window.");
mainWindowManipulationService.Maximise();
Log.InfoFormat("Setting opacity to 1 (fully opaque)");
mainWindowManipulationService.SetOpacity(1);
`

**Comment by annakirkpatrick** [comment] 2019-03-01 17:14
@JuliusSweetland sorry for the delayed response. I just saw this.

I don't have any personal need for a full-screen dynamic keyboard, but I would be willing to take a look at the code and see if I can implement what is needed.

I probably would not be able to get to it until after my thesis proposal defense at the end of the month (that is, until sometime in April).

**Comment by JuliusSweetland** [comment] 2019-03-01 17:21
Perfect, thanks. Best of luck for your thesis defence.

**Comment by JorgeMattos** [comment] 2019-03-01 20:32
@annakirkpatrick 
Best of luck for your thesis defence.
Thank you very much.

**Comment by JorgeMattos** [comment] 2019-03-05 12:14
@JuliusSweetland  Is the work here github going to continue?

**Comment by JuliusSweetland** [comment] 2019-03-05 12:16
@JorgeMattos Are you asking in response to this: https://github.com/OptiKey/OptiKey/issues/544 ?

Yes, the project isn't moving. It isn't changing. It isn't going away. It isn't being monetised. Everything continues as it was. All that is changing is that the copyright will be transferred into a limited company.

**Comment by JorgeMattos** [comment] 2019-03-05 12:24
Great! I love this project.
Thank you very much, my friend.  :—)

**Comment by JuliusSweetland** [comment] 2019-03-05 12:26
And thank you!

**Comment by JuliusSweetland** [comment] 2019-04-02 15:05
@JorgeMattos I'm going to re-open this issue as @annakirkpatrick said she may be able to look into this when she is next free.

**Comment by JorgeMattos** [comment] 2019-04-02 15:41
@JuliusSweetland Excuse me. I'm thinking of writing a simplified Portuguese keyboard, I believe it's the best way to optimize Optikey for those who have not been able to use conversation.
Thank you very much.

**Comment by JuliusSweetland** [comment] 2019-04-02 15:50
Sounds like a great idea

**Comment by alexandre-mbm** [comment] 2020-08-10 16:50
@JorgeMattos 

https://github.com/OptiKey/OptiKey/issues/536#issuecomment-459450825

> All the dynamic keyboards I created worked perfectly.

Where are?

https://github.com/OptiKey/OptiKey/issues/536#issuecomment-479058132

> I'm thinking of writing a simplified Portuguese keyboard, I believe it's the best way to optimize Optikey for those who have not been able to use conversation.

Did you it?

**Comment by JorgeMattos** [comment] 2020-09-07 10:25
I didn't make a friend, I don't believe in effective!

________________________________
De: Alexandre Magno <notifications@github.com>
Enviado: segunda-feira, 10 de agosto de 2020 14:50
Para: OptiKey/OptiKey <OptiKey@noreply.github.com>
Cc: Jorge Mattos <jorgedimattos@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [OptiKey/OptiKey] Possibility of creating a Dynamic keyboard for the conversation mod? (#536)


@JorgeMattos<https://github.com/JorgeMattos>

#536 (comment)<https://github.com/OptiKey/OptiKey/issues/536#issuecomment-459450825>

All the dynamic keyboards I created worked perfectly.

Where are?

#536 (comment)<https://github.com/OptiKey/OptiKey/issues/536#issuecomment-479058132>

I'm thinking of writing a simplified Portuguese keyboard, I believe it's the best way to optimize Optikey for those who have not been able to use conversation.

Did you it?

**Comment by JorgeMattos** [comment] 2020-09-07 12:29
> @JorgeMattos
> 
> [# 536 (comentário)](https://github.com/OptiKey/OptiKey/issues/536#issuecomment-459450825)
> 
> > Todos os teclados dinâmicos que criei funcionaram perfeitamente.
> 
> Onde estão?
> 
> [# 536 (comentário)](https://github.com/OptiKey/OptiKey/issues/536#issuecomment-479058132)
> 
> > Estou pensando em escrever um teclado simplificado para o português, acredito que seja a melhor forma de otimizar o Optikey para quem não tem conseguido usar a conversação.
> 
> Você fez isso?

——Hello, what kind of dynamic keyboard does your father Antonio need? I made a dynamic keyboard once, after I put the native (-) key he chose to use the native keyboard.
I like the way he uses Optikey, write on the conversation screen then copy and paste using (CTRL + V).
Unfortunately Optikey does not accept ASCII = &#22;

**Comment by JorgeMattos** [comment] 2020-09-07 12:37
> @JorgeMattos
> 
> [# 536 (comentário)](https://github.com/OptiKey/OptiKey/issues/536#issuecomment-459450825)
> 
> > Todos os teclados dinâmicos que criei funcionaram perfeitamente.
> 
> Onde estão?
> 
> [# 536 (comentário)](https://github.com/OptiKey/OptiKey/issues/536#issuecomment-479058132)
> 
> > Estou pensando em escrever um teclado simplificado para o português, acredito que seja a melhor forma de otimizar o Optikey para quem não tem conseguido usar a conversação.
> 
> Você fez isso?

Hello, what kind of dynamic keyboard does your father Antonio need? I made a dynamic keyboard once, after I put the native (—) key he chose to use the native keyboard.
![Capturar](https://user-images.githubusercontent.com/39384525/92388443-a8e95200-f0ed-11ea-9272-4d169583ee6d.PNG)

I like the way he uses Optikey, write on the conversation screen then copy and paste using (CTRL + V).
Unfortunately Optikey does not accept ASCII = &#22 ;

**Closed** 2020-09-07 12:43 UTC
Labels: STATUS:help wanted, TYPE:improvement

**Comment by alexandre-mbm** [comment] 2020-09-09 14:21
@JorgeMattos:
> I didn't make a friend, I don't believe in effective!

Não sei se entendi isto que você tentou escrever em inglês.

@JorgeMattos:
> Hello, what kind of dynamic keyboard does your father **Antonio** need?

O nome dele é **Alberto**.

Não sei o que ele tem desejado ultimamente. Fiz uma pergunta a ele hoje, nesse sentido, mas ainda não fui respondido.

**Comment by alexandre-mbm** [comment] 2020-09-09 14:40
@JuliusSweetland, see this _hint_ please.

---

@JorgeMattos:
> I like the way he [Alberto] uses Optikey, write on the **conversation screen** then copy and paste using (`CTRL + V`).

It would be better if the Conversation Keyboard can be retracted for actions on chats screens.
