### ISSUE TITLE
MaryTTS no voices choice.

### ISSUE THREAD

**Issue by Sheeva007** [OptiKey/OptiKey#353] opened 2017-08-22 18:47 UTC
I have installed MaryTTS as preconized and checked "use MaryTTS" in sound settings window but, when i try to select voice to use this stay empty.

So, i have started marytts-server.bat from the console, everythink start correctly. Then, i try to run component-installer ,in my case french pierre. And again everything is available and operational. I can ear this very realistic french voice. Under Optikey... Nothing append. No error. No voice.

Thx.

**Comment by zelmon64** [comment] 2017-08-22 19:23
If it's configured correctly, marytts-server.bat should be started and closed automatically with OptKey. When you checked `use MaryTTS` you should then have clicked on the button below and located the marytts-server.bat file. Then after closing the management console OptiKey should restart and the available MaryTTS voices should be listed in the management console.

**Comment by Sheeva007** [comment] 2017-08-23 17:47
@zelmon64 Same behavior here. No MaryTTS server console started While optikey run. I give up for now. i will continue with **eSpeak** crapy voices.

**Comment by JuliusSweetland** [comment] 2017-08-23 20:18
@Sheeva007 Can you try manually running marytts-server.bat before OptiKey starts (and have MaryTTS enabled in the Management Console) - let us know if that works.

**Comment by Sheeva007** [comment] 2017-08-24 17:44
@JuliusSweetland It's working manually. With english-female voice (default voice i présume)

**Comment by JuliusSweetland** [comment] 2017-08-24 17:57
Thank you. If you close MaryTTS and then let OptiKey start it up, by
starting OptiKey, do you see a command prompt open with MaryTTS? If not
could you upload or email your logs?

**Comment by Sheeva007** [comment] 2017-08-24 18:52
@JuliusSweetland I will try to be clear... If i start MaryTTS server manually then optikey it's working like i said before. But, if i go to management window in sound section i can select other voices included with MaryTTS package. So i'm feeling like a super hero :-) t'ill i press ok ...optikey very kindly crash.
I confirm. The MaryTTS server is not started by Optikey. I send you log file later.(my wife is waiting for me)

**Comment by JuliusSweetland** [comment] 2017-08-24 19:02
Ok thank you. Your log file will be very helpful. When OptiKey crashes
(actually when you next start it) it emails me the crash log so I can see
what happened - I believe I can see your crash. It doesn't look like it has
anything to do with MaryTTS. Can you try changing any other (non-MaryTTS)
setting in the Management Console and clicking OK - I suspect it will crash
also.

**Comment by JuliusSweetland** [comment] 2017-08-24 19:17
@zelmon64 If you're interested I believe this is the crash log. I'm preparing v2.11.0 pre-release of OptiKey with upgraded Mah Apps (and other NuGet packages) hoping that the bug is with Mah Apps and they have fixed it...

2017-08-24 20:31:16,654 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: KeySelectionResult received with string value '' and function key values 'MouseMoveAndLeftClick'
2017-08-24 20:31:16,654 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Mouse move and left click selected.
2017-08-24 20:31:16,654 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: SelectionMode changed to Point
2017-08-24 20:31:19,239 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Selection event received from InputService.
2017-08-24 20:31:19,239 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Executing nextPointSelectionAction delegate with point '1761,944'
2017-08-24 20:31:19,266 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: SelectionResult event received from InputService.
2017-08-24 20:31:21,904 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Selection event received from InputService.
2017-08-24 20:31:21,912 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Performing mouse left click at point (1773,944.666666666667).
2017-08-24 20:31:21,912 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Releasing modifiers (shift:Up, ctrl:Up, win:Up, alt:Up)
2017-08-24 20:31:21,912 [ 1] INFO  JuliusSweetland.OptiKey.Services.AudioService: Playing sound 'Resources\Sounds\MouseClick1.wav' at volume '100'
2017-08-24 20:31:21,929 [ 1] INFO  JuliusSweetland.OptiKey.Services.PublishService: Simulating clicking the left mouse button click
2017-08-24 20:31:21,939 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Restoring modifiers (shift:Up, ctrl:Up, win:Up, alt:Up)
2017-08-24 20:31:21,939 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: SelectionMode changed to Key
2017-08-24 20:31:21,939 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: SelectionResult event received from InputService.
2017-08-24 20:31:22,035 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.ManagementViewModel: Applying management changes
2017-08-24 20:31:22,263 [ 1] INFO  JuliusSweetland.OptiKey.Services.DictionaryService: LoadDictionary called. Keyboard language setting is 'FrenchFrance'.
2017-08-24 20:31:25,231 [ 1] ERROR JuliusSweetland.OptiKey.App: A DispatcherUnhandledException has been encountered...
System.ComponentModel.Win32Exception (0x80004005): Paramètre incorrect
   à Microsoft.Windows.Shell.WindowChromeWorker._HandleMoveForRealSize(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   à Microsoft.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   à System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by JuliusSweetland** [comment] 2017-08-24 19:26
@Sheeva007 After seeing if any Management Console OK click crashes OptiKey could you try this pre-release and see if it fixes anything (it's a long shot!):

https://github.com/OptiKey/OptiKey/releases/tag/v2.11.0_pre-release_1

**Comment by zelmon64** [comment] 2017-08-24 19:51
@JuliusSweetland Cheers for the log. MaryTTS is automatically disabled if it doesn't know the location of marytts-server.bat or can't start it so I agree this probably isn't caused by MaryTTS. 

Is it an issue that AppVeyor isn't liking v2.11.0?

@Sheeva007 To manually change the MaryTTS voice without the management console edit the `"\AppData\Roaming\JuliusSweetland\OptiKey.exe_Url_<instance_identifier>\<version>\user.config"` file with the line:

```
            <setting name="MaryTTSVoice" serializeAs="String">
                <value><MaryTTS_voice_name></value>
            </setting>
```
such as
```
            <setting name="MaryTTSVoice" serializeAs="String">
                <value>dfki-spike-hsmm en_GB male hmm</value>
            </setting>
```
or in your case I'm guessing
```
            <setting name="MaryTTSVoice" serializeAs="String">
                <value>upmc-pierre-hsmm fr male hmm</value>
            </setting>
```

**Comment by JuliusSweetland** [comment] 2017-08-24 19:58
I have just fixed AppVeyor by the way. Thanks.

**Comment by zelmon64** [comment] 2017-08-25 08:51
@Sheeva007 according to that log file your MaryTTS is at `C:\install\marytts-5.2\bin\marytts-server.bat` and it is being started. Are you certain you don't see the terminal appear along your taskbar containing the MaryTTS server and is that the correct location? Now when you go into the management console are there any voices listed for MaryTTS?

**Comment by Sheeva007** [comment] 2017-08-25 10:51
@JuliusSweetland did you try with abslute/relative path ?

**Comment by zelmon64** [comment] 2017-08-25 13:08
@Sheeva007 In that case it's definitely not starting the MaryTTS server. I don't know why it's not giving an error when trying to start it. I believe it should work with either absolute or relative paths but the location of `marytts-server.bat` is kept as absolute.

Have you tried manually running the MaryTTS server to see if you can now use the Pierre voice?

As an alternative have you already tried using the French Mbrola voices through espeak?

**Comment by Sheeva007** [comment] 2017-08-25 14:00
@zelmon64 In this case (fully manual) it's working as expected and, select 'pierre' in management sound tab i can press OK or CANCEL without Optikey Crash. Then i quit optikey nicely. next optikey run my prefered voice 'pierre' disapeard...  all this to say, optikey didn't start MaryTTS server at begining.

I use : 
Optikey 2.11.0 pre-release
MaryTTS 5.2
Full privilège on win10

Thx for your work anyway.

**Comment by zelmon64** [comment] 2017-08-25 15:26
@Sheeva007 Does that mean the MaryTTS server was closed automatically by OptiKey or did you just leave that step out? 

I put my MaryTTS in the same location as yours to make sure that wasn't the problem and it isn't. I also checked that it runs with and without admin privileges and it does. 

Until we get to the bottom of this at least it works when you start it manually.

**Comment by zelmon64** [comment] 2017-08-25 16:56
@Sheeva007 Could you please replace your `OptiKey.exe` file with the attached version? I've added some checks to when the MaryTTS server is started in the hope that it may show what's wrong. It should also try to restart the server if it fails when using the speak key (and switches to the normal voice if that also fails).

[OptiKey_v2.11.0_p1.zip](https://github.com/OptiKey/OptiKey/files/1252472/OptiKey_v2.11.0_p1.zip)

Once you've tried it please post your log file.

**Comment by Sheeva007** [comment] 2017-08-25 17:38
@zelmon64 ASAP

**Comment by JuliusSweetland** [comment] 2017-08-25 20:59
@zelmon64 v2.11.0 is now on pre-release_2

If you have any time could you try it out and see if it feels stable. My tests are all good so far.

The changes are:
Upgrades all referenced NuGet packages
Performance improvements to the way dictionary entries are managed in memory and persisted to disk

**Comment by zelmon64** [comment] 2017-08-26 09:25
@JuliusSweetland v2.11.0_pre-release_2 seems to have a problem with the CommuniKate keyboard (you've probably received a few crash emails from me sorry). I'll see if I can find he problem.

**Comment by zelmon64** [comment] 2017-08-26 10:10
@JuliusSweetland The problem seems to be with the [unzipping stage of using the CommuniKate pageset](https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey/UI/Controls/CK20Page.xaml.cs#L848-L851). If I change the `System.IO.Compression` version information in [JuliusSweetland.OptiKey.csproj](https://github.com/OptiKey/OptiKey/blob/eccc3dac7a2c7d758e9b3bf6c42e3a119d107ed9/src/JuliusSweetland.OptiKey/JuliusSweetland.OptiKey.csproj#L126-L127) and [packages.config](https://github.com/OptiKey/OptiKey/blob/eccc3dac7a2c7d758e9b3bf6c42e3a119d107ed9/src/JuliusSweetland.OptiKey/packages.config#L19) all to `4.0.0` then it works for me. I'm not sure what the latest version is or what the difference would be by using the old `4.0.0` version. How do you think we should handle this?

**Comment by JuliusSweetland** [comment] 2017-08-26 10:26
Ok thanks. No rush. I'm not going to release it yet.

**Comment by JuliusSweetland** [comment] 2017-08-26 10:30
Is the compression stuff a stand alone NuGet package? If it is then we
could roll back the version. I blindly upgraded everything, which is often
a stupid idea!

**Comment by zelmon64** [comment] 2017-08-26 10:38
@JuliusSweetland If I understand correctly I think it's a separate package. I'll make a PR.

**Comment by JuliusSweetland** [comment] 2017-08-26 11:08
Great thank you.

**Comment by Sheeva007** [comment] 2017-08-26 11:12
@zelmon64 My logfile.
[OptiKey.log.txt](https://github.com/OptiKey/OptiKey/files/1253588/OptiKey.log.txt)

**Comment by Sheeva007** [comment] 2017-08-26 11:34
@zelmon64 After an error about log file here is the good one.My log. Oups.
[OptiKey.log.txt](https://github.com/OptiKey/OptiKey/files/1253601/OptiKey.log.txt)

**Comment by zelmon64** [comment] 2017-08-26 12:20
> 2017-08-26 13:20:43,445 [ 1] INFO  JuliusSweetland.OptiKey.App: Trying to start MaryTTS from 'C:\install\marytts-5.2\bin\marytts-server.bat'.
> 2017-08-26 13:20:43,493 [ 1] INFO  JuliusSweetland.OptiKey.App: Started MaryTTS at 08/26/2017 13:20:43.
> .
> .
> .
> 2017-08-26 13:25:11,515 [ 1] INFO  JuliusSweetland.OptiKey.App: MaryTTS has already been closed.

@Sheeva007 This is interesting. It looks like the MaryTTS server is being started okay but then soon closed by something. Would it be possible for you to temporarily disable any antivirus software you have and see if the server stays open? I can't think what else may be closing it.

**Comment by JuliusSweetland** [comment] 2017-08-26 12:34
It may not be starting correctly. Is there any debugging info on the
process that OptiKey starts that could be output to see if it has really
started?

**Comment by zelmon64** [comment] 2017-08-26 12:55
@JuliusSweetland I added a [check after starting the MaryTTS server to make sure it is actually started](https://github.com/zelmon64/OptiKey/blob/b677fe892acdcc6ffe310dccfa34aa2d56123e1d/src/JuliusSweetland.OptiKey/App.xaml.cs#L1008-L1013) to the version Sheeva007 just tried. The message `Started MaryTTS at 08/26/2017 13:20:43.
` in the log indicates that check was successful. Do you think that check should be adequate to determine whether the server really has been started or would you recommend a different way to detect it?

**Comment by JuliusSweetland** [comment] 2017-08-26 14:19
Hmm no that's probably sufficient. You don't really have much control over
processes after spawning then.

**Comment by Sheeva007** [comment] 2017-08-26 14:40
@zelmon64 @JuliusSweetland You can close  this issues. The problem come from my side... Shame on me... After updated Java to version 8, optikey start MaryTTS server as required. Sorry guy's. You hate me now and forever. :-(

**Comment by zelmon64** [comment] 2017-08-26 14:47
@Sheeva007 That's great news! What's annoying is that I wondered if Java could be the problem but since the manual starting worked I didn't think it would be. It's very useful to know that Java versions before 8 can be a problem thanks. No hate needed (or allowed) =D.

**Comment by JuliusSweetland** [comment] 2017-08-26 17:38
I'm glad this is sorted. I'll add a note to the MaryTTS wiki page warning
users that old versions of Java can be problematic.

**Closed by JuliusSweetland** 2017-08-26 17:38 UTC
