### ISSUE TITLE
Some accents provoke wrong strings that should not be added to dictionary

### ISSUE THREAD

**Issue by alexandre-mbm** [OptiKey/OptiKey#300] opened 2017-01-07 23:25 UTC
Examples: dicion**á**rio, ben**é**fico, can**çã**o

**Comment by JuliusSweetland** [comment] 2017-01-08 13:12
Which language?
Please provide steps to replicate the issue. What does happen? What do you think should happen?

**Comment by alexandre-mbm** [comment] 2017-01-08 20:23
Portuguese.

Steps:
1. Type a phrase containing accented word
1. Click "Add to dictionary"
1. Asks for each accented word will evidence the problem

**Comment by JuliusSweetland** [comment] 2017-01-08 22:09
@alexandre-mbm The problem is the code which extracts words from the scratchpad. It uses this regex which does not match to characters with diacritics (accents etc):

private const string WordRegex = @"(?:\s*)(([_a-zA-Z0-9-\+]+(\.[_a-zA-Z0-9-\+]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,6}))|(([a-zA-Z]\.){2,})|([a-zA-Z]+(['-][a-zA-Z]+)*))(?:\s*)";

The solution might be to simplify this to just split the scratchpad by white space.

**Comment by alexandre-mbm** [comment] 2017-01-09 00:02
Thanks! I will work in this from now and I want fix it in few hours.

**Comment by JuliusSweetland** [comment] 2017-01-09 08:01
@alexandre-mbm No rush. The regex intention is to identify words and email addresses, but I think a better solution would be to just tokenise on whitespace (split on ' ', '\t', '\n') and use the matches from that.

**Comment by JuliusSweetland** [comment] 2017-01-17 20:22
@alexandre-mbm Hi Alexandre - any luck with this one?

**Comment by alexandre-mbm** [comment] 2017-01-21 08:00
@JuliusSweetland, I am with problems: my brother's remote machine, my time, it is a Windows machine... I have no enthusiasm to technology. I want to help my father but in really I have not enthusiasm with hight-tech world and so I puts little priority to programming. Sorry.

**Comment by JuliusSweetland** [comment] 2017-01-30 23:27
@alexandre-mbm Of course. Absolutely no pressure from me. Spend time with your father.

**Comment by JuliusSweetland** [comment] 2017-01-30 23:54
To be released in v2.3.10

**Closed by JuliusSweetland** 2017-01-30 23:54 UTC
Labels: STATUS:help wanted, TYPE:bug
