### ISSUE TITLE
Play a sound before saying the sentence.

### ISSUE THREAD

**Issue by Sheeva007** [OptiKey/OptiKey#393] opened 2017-10-09 09:06 UTC
we are a family making a lot of noise  while speaking  together ( like many othersi i presume)
So ,it's always difficult for me to let ear my "synthetic" voice. So, playing a beep or a sample (much more funny)  can be a good improvemennt.

Dominique.

**Comment by zelmon64** [comment] 2017-10-09 09:46
@Sheeva007 I believe this is related to #341.

@JuliusSweetland & @csharperperson what approach was decided for #341 and has any progress been made? I'd like to have a go at adding the attention sound key if it hasn't been started already.

**Comment by JuliusSweetland** [comment] 2017-10-09 09:54
@zelmon64 I agree a call button would be useful, rather than playing a sound before **every** spoken output (which would get a bit grating I think).

Where this key lives needs a bit of discussion. The Alpha keyboard is crowded, but it could be very useful there.

**Comment by zelmon64** [comment] 2017-10-09 10:11
@JuliusSweetland I was thinking to either put it right of the menu key or behind the scratchpad like the CK speak key. Either way I thought to probably have it hidden by default and enabled it in the management console.
![image](https://user-images.githubusercontent.com/15001389/31333202-06684336-ace1-11e7-9831-840ffe7a929e.png)

**Comment by JuliusSweetland** [comment] 2017-10-09 10:22
I think the last button on the top row would be a good starting point.

**Comment by zelmon64** [comment] 2017-10-09 10:26
Great, I'll get started on it then.

**Comment by JuliusSweetland** [comment] 2017-10-09 10:28
Great thanks

**Comment by zelmon64** [comment] 2017-10-09 17:13
@JuliusSweetland I've used a Times New Roman exclamation mark for the icon and let it use the GeneralSoundFiles (default tone1).

![image](https://user-images.githubusercontent.com/15001389/31349559-a61b6ad6-ad1b-11e7-928a-8dfe38f76b67.png)

@Sheeva007 Here's a test build. Check `Enable attention key?` on the **Visuals** tab of the **management console**. The attention sound can then be changed on the **Sounds** tab.

https://drive.google.com/open?id=0B7SYYOqNW4FSSFpKR2Ixb3pQN1E

**Comment by JuliusSweetland** [comment] 2017-10-09 17:22
Hi William,

That looks good. I'll take a look this week. One request though; there is
an actual exclamation mark key so I think it would be clearer to use an
"alert" icon, e.g. a bell icon. I am happy to find one, or if you're
interested I tend to source icons from the noun project.

**Comment by zelmon64** [comment] 2017-10-09 18:36
@JuliusSweetland I'm happy to use a different icon. The exclamation mark was just a quick placeholder. I'll see what I can find.

**Comment by Sheeva007** [comment] 2017-10-09 18:49
Thank's guy's. Your way is better to resolve my demand. (exept the icone itself :-) ).
I'm still want to use a sample to customize that a bit.
Anyway, you are always so fast ! Great.

**Comment by zelmon64** [comment] 2017-10-09 20:15
@Sheeva007 I've added the file "\Resources\Sounds\Attention.wav". It's a duplicate of tone1 so you can replace it and select it in the management console.
https://drive.google.com/open?id=0B7SYYOqNW4FSZXNhTkp5LVVRclU

**Comment by JuliusSweetland** [comment] 2017-10-10 08:40
@zelmon64 I've found a candidate icon. Can you create a new "Alarm" symbol using this path:

M19.44,82.77h15.2a15.48,15.48,0,0,0,30.71,0h15.2a8.9,8.9,0,0,0,6.62-14.85L80.34,60.3V46.24A30.4,30.4,0,0,0,62.11,18.45V16.18A12.31,12.31,0,0,0,50.83,3.77,12.12,12.12,0,0,0,37.89,15.86v2.6a30.42,30.42,0,0,0-18.23,27.8v14l-6.84,7.62a8.9,8.9,0,0,0,6.62,14.85ZM50,90.26a9.51,9.51,0,0,1-9.28-7.49H59.28A9.51,9.51,0,0,1,50,90.26ZM17.29,71.93l7.6-8.47a3,3,0,0,0,.77-2V46.26A24.41,24.41,0,0,1,41.89,23.32a3,3,0,0,0,2-2.83V15.86A6.13,6.13,0,0,1,50,9.74h.43a6.3,6.3,0,0,1,5.69,6.42v4.31a3,3,0,0,0,2,2.83A24.39,24.39,0,0,1,74.34,46.24V61.45a3,3,0,0,0,.77,2l7.6,8.47a2.9,2.9,0,0,1-2.16,4.84H19.44a2.9,2.9,0,0,1-2.16-4.84Z

If it looks good could you please add this to the src\CREDITS.txt file (in the icons section):

Alarm icon from: Bell by Adiyogi from the Noun Project (thenounproject.com)

**Comment by JuliusSweetland** [comment] 2017-10-10 08:42
@zelmon64 The other thing I was thinking about is where this key could go on other language Alpha keyboards as not all of them have a spare space. I don't have an answer to that yet. I was mulling over whether to optionally (from a setting) include the alarm key next to the scratchpad, but it makes everything unbalanced. Hmm...

**Comment by zelmon64** [comment] 2017-10-10 10:30
@JuliusSweetland Thanks for finding the icon. It looks good. I added the credits and it reminded me that I hadn't done that for the Browser icons so I added them as well.
![image](https://user-images.githubusercontent.com/15001389/31381456-7d089628-adac-11e7-88f6-1416ca78950b.png)

I've also added a proper find button for the custom attention sound and removed Attention.wav. The supported formats appear to be `(*.aac;*.mp3;*.mp2;*.mp1;*.ogg;*.wav;*.aiff)` but I included the `All files (*.*)` option as well in case there are more.

https://drive.google.com/open?id=0B7SYYOqNW4FSX1JpaHlsenlIRTA

**Comment by JuliusSweetland** [comment] 2017-10-10 10:40
@Sheeva007  Could you please test and let us know what you think.

@zelmon64 Great stuff thanks. Once we have some testing feedback I'd be happy to get a PR.

**Comment by Sheeva007** [comment] 2017-10-10 13:21
@JuliusSweetland The bell exist only with the english layout. I'm using french layout.. But, about my satisfaction is very close to 100% !

**Comment by JuliusSweetland** [comment] 2017-10-10 14:11
Good news. The challenge now is to find somewhere on every alpha (letters)
keyboard in every language. The alternative might be to put it on the menu,
but that only works if it would be used occasionally to get attention.
Thoughts?

**Comment by zelmon64** [comment] 2017-10-10 15:10
@Sheeva007 I'm glad you're liking it so far.

@JuliusSweetland I see the French alpha keyboard has a double-spaced menu key as well as an empty space but as you said, this isn't the case for all of the languages. I feel like for the time being it would be best to put the alarm key next to the scratchpad and sacrifice the symmetry. If it comes to it perhaps we could add another key the other side of the scratchpad (or even put a half sized alarm key either side of it).

![image](https://user-images.githubusercontent.com/15001389/31393008-95a2b4a4-add2-11e7-880d-ee77a76022f9.png)

**Comment by zelmon64** [comment] 2017-10-10 16:22
I think it doesn't look too unbalanced. 
![image](https://user-images.githubusercontent.com/15001389/31397381-c3aacee4-addd-11e7-9bab-2cdb5127447a.png)

https://drive.google.com/open?id=0B7SYYOqNW4FSU0xTQ2pKWEkxYTA
(I only packaged OptiKey.exe since that is the only file which is different to Optikey_v2.11.0_pre-release_7_custom03)

**Comment by Sheeva007** [comment] 2017-10-10 16:30
@zelmon64 I love your bell icon placement . A more intuitive would be at the begining of sentence... But,both of them put my satisfaction far over 100%.

**Comment by JuliusSweetland** [comment] 2017-10-10 16:46
@zelmon64 I might change the icon later this week when I have some time to look. It looks a bit tall and thin to my eyes. In terms of positioning, maybe on the left of the scratchpad would be better? Two considerations:

1.The setting for the default key selection times will need to be amended to include this new key. I would suggest setting the selection time to 2 seconds
2.If the alert key is enabled then the scratchpad width would need to be reduced by 1 key width. This logic should probably live in the Output.xaml control.

**Comment by Sheeva007** [comment] 2017-10-13 07:36
@JuliusSweetland @zelmon64 i use version 2.11 custom for a couple of day without encountering any problems. Bravo guy's. Excellent job. :-)

**Comment by JuliusSweetland** [comment] 2017-10-14 21:43
@Sheeva007 Great. I'll close this issue. Version 2.11.0 will be released officially very soon.

**Closed by JuliusSweetland** 2017-10-14 21:43 UTC
Labels: STATUS:help wanted, TYPE:improvement
