### ISSUE TITLE
Fix dock flickering when changing from floating to docked, or changing dock size

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#98] opened 2015-09-15 18:34 UTC
http://stackoverflow.com/questions/18491178/app-bar-window-pops-away-from-docking-postion-then-moves-into-the-docking-posit

**Comment by SamPlusPlus** [comment] 2015-12-29 02:25
How do you reproduce this?

**Comment by JuliusSweetland** [comment] 2015-12-29 05:44
If you are docked then use the "Size & Position" keyboard to move away from
docked edge. OptiKey will break away from the edge and flicker while it
resized. Similarly it will flicker when resized while docked, or if you
move it back to an edge and cause it to dock again from floating.

**Comment by Pakosoft** [comment] 2016-11-04 16:26
Hi Julius,

I'm an experienced programmer but a complete noob in Github. I find this project very interesting and like to collaborate trying to fix bugs like this one. I can run the solution on my computer with no initial problems. I read that you can collaborate on someone's project by following these steps:

1. Fork the target repo to your own account.
2. Clone the repo to your local machine.
3. Check out a new "topic branch" and make changes.
4. Push your topic branch to your fork.
5. Use the diff viewer on GitHub to create a pull request via a discussion.
6. Make any requested changes.
7. The pull request is then merged (usually into the master branch) and the topic branch is deleted from the upstream (target) repo.

Do you think this is the best way I could start or would you do it differently?

Thank you,
Francisco.

**Comment by JuliusSweetland** [comment] 2016-11-05 20:03
Hi there. Yes that work flow sounds right. Step 3 is optional. If you want
to work on a single bug or feature you can clone the OptiKey master branch,
fix the issue, and then create a pull request. I can test the fix before I
merge it in.

Git and GitHub can be a bit tricky, so let me know if you have any
questions.

**Comment by Pakosoft** [comment] 2016-11-06 01:32
Alright then, Thank you very much.

**Comment by Pakosoft** [comment] 2016-11-07 19:34
Hi Julius,

I can't reproduce the issue. I took the following steps in debug mode in VS 2015:

1.- Go to Menu
2.- Go to Size and position
3.- I tried expanding, shrinking, moving and jumping. I started from having the keyboard in a docked position and from that point it changed without any noticeable flickering.

I have a question though:

How can I get back to a docked position?

Francisco.

**Comment by JuliusSweetland** [comment] 2016-11-07 19:36
Hi Francisco. If you move OptiKey to and edge and then continue moving so
OptiKey is moving over the screen edge then it will dock to that edge. I
believe this issue is a flicker during that dock/undocking state change.

**Closed** 2017-10-26 10:56 UTC
Labels: STATUS:help wanted, TYPE:bug
