### ISSUE TITLE
Releasing keys in dynamic keyboard

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#634] opened 2020-01-27 11:52 UTC
I've been playing with @AdamRoden's latest changes to the dynamic keyboards, and wanted to give some feedback / open a discussion about key releasing.

As a case study, I made a keyboard for a strategy game - Kingdom: New Lands, which is a nice example because controls are limited (WASD only) but a bit nuanced (requires keys to be held down for a certain time to register a key press, sometimes requires holding down keys, or tapping quickly). 

First impressions - the new system is really flexible and let me do things I didn't expect to be easy - in particular, it didn't take long to figure out a set of actions that would be the equivalent of "double tap to start galloping and then keep held down" as a toggle-able key. It was really quick and easy to get something working, so thanks a lot for the contribution - I'm really excited about using it for gaming. 

This is what it looks like:
keyboard: [Keyboard gist](https://gist.github.com/kmcnaught/97322f323abdfa3a15996e612a39a0e5)
video: [Kingdom + Optikey video 1](https://www.loom.com/share/79cc334bda0c43ad89aae239785a3a65) 

I'm pretty pleased with this as a first attempt, but there's one bit of functionality that I think could make it even better - the ability to release 'other' keys when you hold down a new one. At the moment you always need to turn off your current action, e.g. 
- turn on walk right
- turn off walk right
- turn on gallop right

...otherwise the keys all interact with each other (e.g. left and right cancel out, or gallop's toggle state is wrong). 

It would be great if you could effectively have an exclusive group of actions, but still have the visual feedback of keys being held down. 

Here's a video of what I'm envisaging (ish), but I hacked it in really poorly for now (the key releases are synchronous so it's slow to click). 
[Kingdom + Optikey video 2](https://www.loom.com/share/cdd224564ddd4358bfebe819ced8f9f2)

I was wondering if either of you had suggestions for the best way to incorporate this properly. Here are some things I've tried/considered, initial and discussion points/concerns:
- The concept of "releasing a key" is a bit ambiguous - in Optikey you want "keys that are held down to be released" (where 'key' may have various actions attached to it), but on a system level you (sometimes) want a physical 'keydown' event sent - sometimes these two things are connected, but not always.
- On a system level you can perhaps use individual `KeyUp` actions to achieve the goal, e.g. 'Move Left' could be `KeyUp(d)KeyToggle(a)` (pseudo-code), but in this case you lose the visual "releasing of Optikey keys", because you wouldn't release the corresponding 'MoveRight' key, which is associated with a StepList value rather than `d`.
- If you do use KeyUp, is it safe to send the system a key release event, even if maybe the key isn't currently pressed? We can check whether it's "down" in `keyStateService.KeyDownStates`, but then we are assuming that's always in sync with the system. Maybe it's totally safe to send a release event anyway, I don't know. 
- On an Optikey level you could perhaps achieve this with a "ReleaseAll" method like:
```
foreach (var key in keyStateService.KeyDownStates.Keys)
{
    KeyDownStates state = keyStateService.KeyDownStates[key].Value;
    if (state != KeyDownStates.Up)
    {
     await keyboardOutputService.ProcessSingleKeyPress(key.String, KeyPressKeyValue.KeyPressType.Release);
     keyStateService.KeyDownStates[key].Value = KeyDownStates.Up;
   }
}
```
... but this would need to handle what it means to release a key such as "MouseMagnifier" which doesn't have an action associated with it. (or any other kind of key that isn't just a 'physical key to be pressed'). 
- If you lose the 'toggle' feedback by using KeyDown instead, you'd really need to be able to have a "ReleaseAll" button so that you know how to get back to a clean state. Though this could be implemented manually with something like `KeyUp(w)KeyUp(a)KeyUp(s)KeyUp(d)`

In summary, the main options visible to me right now are along these lines:
1) Add a "ReleaseAll" action for StepLists. 
- you'd have to specifically handle how this works with a toggle key (e.g. cache current state, then release everything, then apply correct 'toggle' state). 
- you'd have to consider what happens to keys that aren't just "physical keys to be pressed" - are the keys effectively pressed again to release them and perform associated actions? What does this mean for StepList keys and/or KeyToggles (I haven't thought through all the possible considerations here
- this does have the downside of not allowing more fine-grained control over releasing keys, e.g. maybe you want WASD to be mutually exclusive, but not switch off other keys?

2) Use current system with liberal sprinkling of KeyUp events, and keys which are KeyDown only rather than KeyToggle. 
- we'd have to consider whether this is safe from a system perspective
- you'd lose the visual feedback of a key being held down, which is actually pretty valuable as a user. 
- In this case 'ReleaseAll' could be implemented with a bunch of specific `KeyUp` actions rather than an extra Optikey action, which would let you treat different subsets of keys separately (and all this logic would be handled by the dynamic keyboard, not requiring extra Optikey logic)

3) Add some kind of concept of 'exclusive groups' to dynamic keyboards, e.g. in my case "gallop left / walk left / walk right / gallop right' would belong to a single exclusive group, perhaps determined just by giving keys an optional `ExclusiveGroup` ID ? And this would implicitly require Optikey to release any that are currently held, if pressing another. 

Any thoughts? 

After typing all this out, I'm leaning towards (3), because it's the least ambiguous in what it would mean, although it's a slightly more complicated idea for users to understand. I've played about with (1) and (2) but have so far put less thought into (3).

**Comment by AdamRoden** [comment] 2020-01-27 19:02
@kmcnaught thanks for the feedback! I'm happy someone has played with and exposed some of the problems of my dynamic keys. I hit the same issues and more when I tried setting up a dynamic keyboard for gaming.

We definitely need a "ReleaseAll" action because dynamic keys do not play nice.

I've realized a core problem with dynamic keys is that because they can be anything, they don't have a straight forward KeyValue like action keys, or text keys 'a', 'b', 'c', etc. As a result, there is not an easy way to have one key reference another key. This also means there is no way for individual key activation time to be specified. I had plans to create dynamic key groups, and use them for styles, activation times, and now maybe your 3rd idea. The problem is that like George R.R. Martin, I've had writer's block for quite a while now.

**Comment by kmcnaught** [comment] 2020-01-28 11:21
@AdamRoden, that's a good point. If I remember correctly, dynamic keys do end up with an entry in `KeyDownStates` (so they can be turned off with a global "ReleaseAll" function), but their KeyValue is not simple enough for a user to specify in the XML. I did wonder about adding an ID to a key so that (locally within a single keyboard file) you could cross-reference them within e.g. a <ReleaseKey> tag. 

Did you happen to figure out what the system implications are of sending non-meaningful key events? (e.g. a KeyRelease event for a key that isn't held down). Is this okay to do, or do we need to be careful in this regard?

**Comment by JuliusSweetland** [comment] 2020-02-05 13:15
@kmcnaught Great suggestions and I'm glad you and @AdamRoden are speaking about this. In regards to your question I would suggest that releasing a key which isn't down is *probably* not harmful, but I would think it worth checking the state of the key before actioning. This assumes that dynamic keys (and step lists) correctly set the key down state at each point. I cannot remember off the top of my head if this is the case...

Lastly, I like the idea of releasing keys by some sort of xml friendly tag. I also like the concept of groups of keys, or a dynamically created group of "all keys on this keyboard" which could be generated when the dynamic keyboard is parsed. This last group could work in the same way as a dynamic keyboard "group" of keys, in that it is just a group with all keys in it that can be referenced from the action of another key.

It's very easy for me to suggest, but how about doing all 3? That gives keyboard designers the choice of influencing one key, a specific group of keys, or all keys on this keyboard. It's the most powerful option in my opinion.

**Comment by AdamRoden** [comment] 2020-02-07 00:04
@JuliusSweetland @kmcnaught 
At a basic level dynamic keys attempt to maintain key down states, but it is not perfect. 

My thoughts are that if we want to go all out, I could add a new element called KeyRef. Each key could have a list of KeyRef values. If any of the values in the list are matched in a key up event, the key would be released. The default group that every key would belong to would be called 'All'.

**Comment by JuliusSweetland** [comment] 2020-02-07 14:23
@AdamRoden Sounds interesting. Could a key belong to multiple groups? In other words if a key belongs to a more specific group it must still belong to All.

**Comment by AdamRoden** [comment] 2020-02-07 14:54
@JuliusSweetland Yes, a key could be in multiple groups. It would be a many-to-many relationship between keys and key groups. An example would be if you created a 'letters' group and a 'vowels' group and then you included both groups in the key definitions for letters a, e, i, o, and u. The All group will exist by default without having to be defined in the xml.

**Comment by JuliusSweetland** [comment] 2020-02-07 19:57
@AdamRoden Ok that sounds like a good solution then. I'm looking at your email now...

**Comment by AdamRoden** [comment] 2020-02-13 15:41
@JuliusSweetland I'm preparing the solution I proposed but ran into a concern. I need to share a KeyValueByReference dictionary that is visible to both the DynamicKeyboard class and the MainViewModel.ServiceEventHandlers class. My plan is to host the new dictionary in the KeyStateService class which means that to expose my new dictionary for population, I need to pass IKeyStateService from MainViewModel to DynamicKeyBoard. 

Do you agree with this approach?

**Comment by JuliusSweetland** [comment] 2020-02-13 16:41
Yes that would work. You would expose your dictionary as a property in the
main view model and bind it one way to the keyboard host, then pass it onto
the dynamic keyboard as it is created (on the constructor?).

**Comment by AdamRoden** [comment] 2020-02-24 02:20
@kmcnaught If you're still interested you should take a look at my PR and maybe try pulling the code from my fork into one of your branches to try it out. I'd be interested to hear your thoughts on how well it works for you and if you have any recommendations.

**Comment by JuliusSweetland** [comment] 2020-02-24 10:17
@AdamRoden @kmcnaught FYI I will be reviewing the latest dynamic keyboard PR now so hopefully this will be merged and ready to test soon.

**Comment by AdamRoden** [comment] 2020-09-01 16:36
@JuliusSweetland @kmcnaught Closed?

**Closed** 2020-09-01 18:44 UTC
